<?php
    $total_paginas = ceil($totalregistro / $por_pagina);
?>

    <h1>Admin Logueado Satisfactoriamente</h1>
    <h2>
        Agrega (Mostrar):
    </h2>
    <ul>
        <li><p>Paginacion</p></li>
    </ul>
    <a href="<?= BASE_URL;?>admin/agregaUsuarios"><input type="button" value="Agrega Usuario"></a>
    <table class="highlight centered">
        <thead>
            <tr>
                <th scope="col">Cedula</th>
                <th scope="col">Nombre</th>
                <th scope="col">rol ID</th>
                <th scope="col">direcc</th>
                <th scope="col">Telefono</th>
                <th scope="col">Activo</th>
                <th scope="col">Botones</th>
            </tr>
        </thead>
        <tbody>
        <?php 
        
        $tamanio = count($dataAdmin);
        for ($i = 0; $i < $tamanio; $i++){ ?>
            <tr> 
            <td> <?= $dataAdmin[$i]['cedula'] ?> </td> 
            <td> <?= $dataAdmin[$i]['nombre'] ?> </td> 
            <td> <?= $dataAdmin[$i]['nombrerol'] ?> </td> 
            <td> <?= $dataAdmin[$i]['direccion'] ?> </td> 
            <td> <?= $dataAdmin[$i]['telefono'] ?> </td> 
            <td> <?= $activado = ($dataAdmin[$i]['activo'] != 1)? "Bloqueado":"Activo" ?> </td>
            <td>
                <form action="<?=BASE_URL?>admin/agregaUsuarios" method="POST">
                    <input type="hidden" name="modificacion" value="<?=$dataAdmin[$i]['cedula'] ?>">
                    <button name="accion" value="Modificar">Modificar</button>
                    <button name="accion" value="Borrar">Borrar</button>
                </form>
            </td>
            </tr>
            <!-- // como el parametro de si esta activo el usuario o bloqueado es un numero
            //se comprueba con codigo si es esta activo (1) o si esta bloqueado (0 o en este caso cualquier cosa) -->
        <?php 
            }
        ?>
        </tbody>
    </table>
    <div class="col-md-12 center text-center cyan lighten-2"><!--Paginador-->
    <ul class="pagination">
        <?php if($pagina != 1){ ?>
            <li class="waves-effect blue-text"><a href="<?=BASE_URL?>admin/mostrarData?pagina=1"><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="waves-effect"><a href="<?=BASE_URL?>admin/mostrarData?pagina=<?=$pagina - 1?>"><i class="material-icons">chevron_left</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i></a></li>
    <?php
        } ?>
        
        
        <?php for($i = 1; $i <= $total_paginas; $i++){ 
            if ($i == $pagina){ ?>
                <li class="active"><a href="<?=BASE_URL?>admin/mostrarData?pagina=<?=$i?>"><?=$i?></a></li>
           <?php } else{
            ?>
            <li class="waves-effect"><a href="<?=BASE_URL?>admin/mostrarData?pagina=<?=$i?>"><?=$i?></a></li>
        <?php 
            }
        } ?>

        <?php if($pagina != $total_paginas){ ?>
        <li class="waves-effect"><a href="<?=BASE_URL?>admin/mostrarData?pagina=<?=$pagina + 1?>"><i class="material-icons">chevron_right</i></a></li>
        <li class="waves-effect"><a href="<?=BASE_URL?>admin/mostrarData?pagina=<?=$total_paginas?>"><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
    <?php
        } ?>
    </ul>
</div>