<?php
    getHeader($titulo, "headerAdmin");

    getNav("navAdmin");
?>

    <h1>Admin Logueado Satisfactoriamente</h1>
    <table class="table table-dark table-striped w-50 text-center">
        <!--
            print_r($dataAdmin);
        aca se reciben los datos de la consulta de admin 
        por la var que se creo en Admincontroller(consultaData)
        la del array $data['dataAdmin']
        se pasa por su nombre gracias a que al generar la vista en el metodo
        loadview lo pasamos por alli por la variable $$key
        esta en el general controller se puede mostrar de manera de tabla asi:
        -->
        <thead>
            <tr>
                <th scope="col">Cedula</th>
                <th scope="col">Nombre</th>
                <th scope="col">rol ID</th>
                <th scope="col">direcc</th>
                <th scope="col">Contraseña</th>
                <th scope="col">Telefono</th>
                <th scopte="col">Activo</th>
            </tr>
        </thead>
        <tbody>
        <?php 
        
        $tamanio = count($dataAdmin);
        for ($i = 0; $i < $tamanio; $i++){
            echo "<tr>" . 
            "<td>" . $dataAdmin[$i]['cedula'] . "</td>" .
            "<td>" . $dataAdmin[$i]['nombre'] . "</td>" .
            "<td>" . $dataAdmin[$i]['nombrerol'] . "</td>" .
            "<td>" . $dataAdmin[$i]['direccion'] . "</td>" .
            "<td>" . $dataAdmin[$i]['contrasenia'] . "</td>" .
            "<td>" . $dataAdmin[$i]['telefono'] . "</td>" .
            "<td>" . $activado = ($dataAdmin[$i]['activo'] != 1)? "Bloqueado":"Activo" . "</td>" .
            "</tr>"; 
            // como el parametro de si esta activo el usuario o bloqueado es un numero
            //se comprueba con codigo si es esta activo (1) o si esta bloqueado (0 o en este caso cualquier cosa)
        }
        ?>
        </tbody>
    </table>
<?php getFooter("footerAdmin"); ?>