<?php
?>

    <h1>Admin Logueado Satisfactoriamente</h1>
    <h2>
        Agrega (Mostrar):
    </h2>
    <ul>
        <li><p>Animales solo para admin (Ya)</p></li>
        <li><p>Albergues (Aun no )</p></li>
        <li><p>Pedidos Adopcion</p></li>
        <li><p>Paginacion</p></li>
        <li><p>Vendedores(Final final)</p></li>
        <li><p>Tiendas Con vendedores y productos por tienda</p></li>
    </ul>

    <h2>
        Agrega (Registrar):
    </h2>
    <ul>
        <li><p>Veterinarios (Ya)</p></li>
        <li><p>Albergue (Ya)</p></li>
        <li><p></p></li>
        <li><p></p></li>
    </ul>
    <h2>
        Agrega (Modificar):
    </h2>
    <ul>
        <li><p>Adopciones</p></li>
        <li><p>Animales</p></li>
        <li><p>Usuarios</p></li>
        <li><p>Tipos Razas y Animal</p></li>
        <li><p>Veterinarios</p></li>
    </ul>
    <a href="<?= BASE_URL;?>admin/agregaUsuarios"><input type="button" value="Agrega Usuario"></a>
    <table class="highlight centered">
        <!--
            print_r($dataAdmin);
        aca se reciben los datos de la consulta de admin 
        por la var que se creo en Admincontroller(consultaData)
        la del array $data['dataAdmin']
        se pasa por su nombre gracias a que al generar la vista en el metodo
        loadview lo pasamos por alli por la variable $$key
        esta en el general controller se puede mostrar de manera de tabla asi:
        -->
        <thead>
            <tr>
                <th scope="col">Cedula</th>
                <th scope="col">Nombre</th>
                <th scope="col">rol ID</th>
                <th scope="col">direcc</th>
                <th scope="col">Telefono</th>
                <th scope="col">Activo</th>
                <th scope="col">Botones</th>
            </tr>
        </thead>
        <tbody>
        <?php 
        
        $tamanio = count($dataAdmin);
        for ($i = 0; $i < $tamanio; $i++){ ?>
            <tr> 
            <td> <?= $dataAdmin[$i]['cedula'] ?> </td> 
            <td> <?= $dataAdmin[$i]['nombre'] ?> </td> 
            <td> <?= $dataAdmin[$i]['nombrerol'] ?> </td> 
            <td> <?= $dataAdmin[$i]['direccion'] ?> </td> 
            <td> <?= $dataAdmin[$i]['telefono'] ?> </td> 
            <td> <?= $activado = ($dataAdmin[$i]['activo'] != 1)? "Bloqueado":"Activo" ?> </td>
            <td>
                <form action="<?=BASE_URL?>admin/agregaUsuarios" method="POST">
                    <input type="hidden" name="modificacion" value="<?=$dataAdmin[$i]['cedula'] ?>">
                    <button name="accion" value="Modificar">Modificar</button>
                    <button name="accion" value="Borrar">Borrar</button>
                </form>
            </td>
            </tr>
            <!-- // como el parametro de si esta activo el usuario o bloqueado es un numero
            //se comprueba con codigo si es esta activo (1) o si esta bloqueado (0 o en este caso cualquier cosa) -->
        <?php 
            }
        ?>
        </tbody>
    </table>
<!--

            <td>
                    
                        <form method="POST">
                            <input type="hidden" name="textid" id="textid" value="<?= $libro['id']; ?>"/>

                            <input type="submit" name="accion" value="Seleccionar" class="btn btn-primary"/>
                            
                            <input type="submit" name="accion" value="Borrar" class="btn btn-danger"/>
                        </form>
                    
                    </td>

-->