<div class="row" style="padding-top: 5%; padding-bottom: 5%;">
    <div class="col s10 login-card white black-text offset-s1">
        <div class="card-panel col s12 indigo white-text center" style="border-radius: 10px; padding-bottom: 20px;">
            <h3>Gestión de Razas</h3>

            <?php
            $identificador = isset($buscarazas[0]['id_raza'])? $buscarazas[0]['id_raza']: "";
            $nombre = isset($buscarazas[0]['nombre'])? $buscarazas[0]['nombre']: "";
            $tipo = isset($buscarazas[0]['id_tipo_2'])? $buscarazas[0]['id_tipo_2']: "";
            $total_paginas = ceil($totalregistro / $por_pagina);
            ?>

            <form action="<?= BASE_URL?>admin/agregaRazaAnimal" method="POST">
            <div class="text-center col s12">
                <div class="center-align" for="filtro">
                    <?php if(isset($_POST['accion'])=="Modificar"){ ?>
                        <h5 class="light"> Modificar raza de animal</h5> <?php } else { ?>
                        <h5 class="light"> Agregar raza de animal</h5> <?php } ?>
                </div>
                <div class="card col s8 offset-s2"  style="border-radius: 10px; padding-bottom: 20px;">
                    <div class="input-field tooltipped col s6" data-position="top" data-tooltip="Nombre del raza de animal">
                        <label class="black-text" for="">Nombre</label>
                        <input class="validate" type="text" name="nombreRaza" value="<?= $nombre?>">
                        <span class="helper-text black-text">ID: <?=$identificador?></span>
                        <input type="hidden" name="identificador" value="<?=$identificador?>">
                    </div>
                    <div class="input-field tooltipped col s6" data-position="top" data-tooltip="Nombre del tipo de animal">
                        <select name="tipoanimal">
                            <option value="0">Selecciona</option>
                            <?php foreach ($tiposAnimales as $key) { ?>
                            <option <?php if($tipo == $key['id_tipo']){ echo"selected"; } ?> value="<?= $key['id_tipo']; ?>"><?= $key['nombre'] ?> </option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="col s12">
                    <?php if(isset($_POST['accion']) == "Modificar") { ?>
                        <a href="<?= BASE_URL;?>admin/razasAnimal">
                            <input class="btn indigo" type="button" value="Volver">
                        </a> 
                    <?php } ?>
                        <button class="tooltipped btn indigo"  data-position="bottom" data-tooltip="Registrar" name="accion" value="<?php if(isset($_POST['accion'])=="Modificar"){ echo "Modificar"; } else {echo"Agregar";} ?>"><i class="large material-icons">chevron_right</i></button>
                    </div>
                </div>
            </div>
            </form>

        </div>

        <div class="col s2 black-text">
            <h4 class="card-panel indigo center white-text" style="border-radius: 10px;">Menú</h4>
            <ul class="card-panel indigo" style="padding-left: 15px; border-radius: 10px;">
                <li class="hover center"><a href="<?= BASE_URL;?>admin/tipoAnimal"><span class="white-text">Tipos de Animales</span></a></li>
                <li class="hover center"><a href="<?= BASE_URL;?>admin/razasAnimal"><span class="white-text">Razas de Animales</span></a></li>
                <li class="hover center"><a href="<?= BASE_URL;?>admin/agregaVeterinarios"><span class="white-text">Veterinarios</span></a></li>
                <li class="hover center"><a href="<?= BASE_URL;?>admin/animales"><span class="white-text">Peludos</span></a></li>
                <li class="hover center"><a href="<?= BASE_URL;?>admin/mostrarData"><span class="white-text">Usuarios</span></a></li>
                <li class="hover center"><a href="<?= BASE_URL;?>admin/albergues"><span class="white-text">Albergues</span></a></li>
                <li class="hover center"><a href="<?= BASE_URL;?>admin/adopciones"><span class="white-text">Adopciones</span></a></li>
                <li class="hover center"><a href="<?= BASE_URL;?>admin/Reportes"><span class="white-text">Reportes</span></a></li>
            </ul>
        </div>

        <div class="col s10">
        <table class="centered">
        <thead class="card indigo white-text">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nombre</th>
                <th scope="col">Tipo Animal</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>

        <?php 
        $tamanio = count($dataRazas);
        for ($i = 0; $i < $tamanio; $i++){ ?>
            <tr>
                <td><?= $dataRazas[$i]['id_raza']  ?></td>
                <td><?= $dataRazas[$i]['nombre'] ?></td>
                <td><?= $dataRazas[$i]['nombreTipo'] ?></td>
                <td>
                    <form action="<?=BASE_URL?>admin/razasAnimal" method="POST">
                    <input type="hidden" name="modificacion" value="<?=$dataRazas[$i]['id_raza'] ?>">
                        <button class="btn tooltipped blue" data-position="bottom" data-tooltip="Modificar Usuario" name="accion" value="Modificar">
                            <i class="large material-icons">edit</i>
                        </button>
                    </form>
                </td>
            </tr> 
        <?php } ?>
        </tbody>
        </table>
        </div>

        <ul class="pagination center">
            <?php if($pagina != 1) { ?>
                <li class="waves-effect blue-text "><a href="<?=BASE_URL?>admin/razasAnimal?pagina=1<?=$filtro != ""? "&filtro=".$filtro: "";?>"><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
                <li class="waves-effect"><a href="<?=BASE_URL?>admin/razasAnimal?pagina=<?=$pagina - 1?><?=$filtro != ""? "&filtro=".$filtro: "";?>"><i class="material-icons">chevron_left</i></a></li>
            <?php } else { ?>
                <li class="disabled"><a href=""><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
                <li class="disabled"><a href=""><i class="material-icons">chevron_left</i></a></li>
            <?php } ?>
                
            <?php for($i = 1; $i <= $total_paginas; $i++){ 
                if ($i == $pagina){ ?>
                    <li class="active indigo"><a href="<?=BASE_URL?>admin/razasAnimal?pagina=<?=$i?><?=$filtro != ""? "&filtro=".$filtro: "";?>"><?=$i?></a></li>
                <?php } else { ?>
                    <li class="waves-effect"><a href="<?=BASE_URL?>admin/razasAnimal?pagina=<?=$i?><?=$filtro != ""? "&filtro=".$filtro: "";?>"><?=$i?></a></li>
                <?php } } ?>

                <?php if($pagina != $total_paginas){ ?>
                    <li class="waves-effect"><a href="<?=BASE_URL?>admin/razasAnimal?pagina=<?=$pagina + 1?><?=$filtro != ""? "&filtro=".$filtro: "";?>"><i class="material-icons">chevron_right</i></a></li>
                    <li class="waves-effect"><a href="<?=BASE_URL?>admin/razasAnimal?pagina=<?=$total_paginas?><?=$filtro != ""? "&filtro=".$filtro: "";?>"><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
                <?php } else { ?>
                    <li class="disabled"><a href=""><i class="material-icons">chevron_right</i></a></li>
                    <li class="disabled"><a href=""><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
            <?php } ?>
        </ul>
        </div>
    </div>
</div>
