<?php
$identificador = isset($buscarazas[0]['id_raza'])? $buscarazas[0]['id_raza']: "";
$nombre = isset($buscarazas[0]['nombre'])? $buscarazas[0]['nombre']: "";
$tipo = isset($buscarazas[0]['id_tipo_2'])? $buscarazas[0]['id_tipo_2']: "";
$total_paginas = ceil($totalregistro / $por_pagina);
?>
    <table class="highlight centered">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nombre</th>
                <th scope="col">Tipo Animal</th>
            </tr>
        </thead>
        <tbody>
        <?php 
        
        $tamanio = count($dataRazas);
        for ($i = 0; $i < $tamanio; $i++){ ?>
            <tr>
            <td><?= $dataRazas[$i]['id_raza']  ?></td>
            <td><?= $dataRazas[$i]['nombre'] ?></td>
            <td><?= $dataRazas[$i]['nombreTipo'] ?></td>
            <td>
                <form action="<?=BASE_URL?>admin/razasAnimal" method="POST">
                    <input type="hidden" name="modificacion" value="<?=$dataRazas[$i]['id_raza'] ?>">
                    <button name="accion" value="Modificar">Modificar</button>
                </form>
            </td>
            </tr> 
            <?php
        }
        ?>
        </tbody>
    </table>
    <div class="col-md-12 center text-center cyan lighten-2"><!--Paginador-->
    <ul class="pagination">
        <?php if($pagina != 1){ ?>
            <li class="waves-effect blue-text"><a href="<?=BASE_URL?>admin/razasAnimal?pagina=1"><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="waves-effect"><a href="<?=BASE_URL?>admin/razasAnimal?pagina=<?=$pagina - 1?>"><i class="material-icons">chevron_left</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i></a></li>
    <?php
        } ?>
        
        
        <?php for($i = 1; $i <= $total_paginas; $i++){ 
            if ($i == $pagina){ ?>
                <li class="active"><a href="<?=BASE_URL?>admin/razasAnimal?pagina=<?=$i?>"><?=$i?></a></li>
           <?php } else { ?>
            <li class="waves-effect"><a href="<?=BASE_URL?>admin/razasAnimal?pagina=<?=$i?>"><?=$i?></a></li>
        <?php 
            }
        } ?>

        <?php if($pagina != $total_paginas){ ?>
        <li class="waves-effect"><a href="<?=BASE_URL?>admin/razasAnimal?pagina=<?=$pagina + 1?>"><i class="material-icons">chevron_right</i></a></li>
        <li class="waves-effect"><a href="<?=BASE_URL?>admin/razasAnimal?pagina=<?=$total_paginas?>"><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
    <?php
        } ?>
    </ul>
</div>

    <div class="card text-center">
    <form action="<?= BASE_URL?>admin/agregaRazaAnimal" method="POST">
        <label for="">Este es el formulario para registrar tipos de animal</label>
        <br>
        <label for="">ID <?= $identificador?></label>
        <input type="hidden" name="identificador" value="<?=$identificador?>">
        <br>
        <label for="">Nombre</label>
        <input type="text" name="nombreRaza" value="<?=$nombre?>">
        <br>
        <select name="tipoanimal">
          <option value="0">Selecciona</option>
          <!--=============================================
            Este es el usuario de fundacion al que se le 
            añadira el albergue nuevo
          ==============================================-->
        <?php 
          foreach ($tiposAnimales as $key) {?>
          <option <?php if($tipo == $key['id_tipo']){ echo"selected"; } ?> value="<?= $key['id_tipo']; ?>"><?= $key['nombre'] ?> </option>
          <?php
          }
        ?>
        </select>
        <button name="accion" value="<?php if(isset($_POST['accion'])=="Modificar"){ echo "Modificar"; } else {echo"Agregar";} ?>">Aceptar</button>
    </form>
    </div>