<?php

echo "Pagina para la toma de decision acerca de que tipo de reporte se quiere presentar";

?>
<!--
	Ahora modificar y que sean especificos osea con and en lugar de or y un catalogo de fundaciones
	en el usuario normal 
-->
<!--Podrias hacer que los reportes salgan en una ventana nueva para no tener que salir del sistema-->
<div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s2"><a class="active" href="#Animales">Animales</a></li>
        <li class="tab col s2"><a href="#Veterinarios">Veterinarios</a></li>
        <li class="tab col s2"><a href="#Usuarios">Usuarios</a></li>
        <li class="tab col s2"><a href="#Albergues">Albergues</a></li>
        <li class="tab col s2"><a href="#General">Bitacoras</a></li>
      </ul>
    </div>

    <div id="Animales" class="col s12">
	<form action="<?=BASE_URL?>report/Bitacora_Animales" target="_blank" method="POST">
			<label>Animales</label><br>
			<label for="">Nombre</label>
			<input type="text" name="NombreAnimal" class="col s6">
			<label for="">Año de Nacimiento</label>
			<input name="Ano_nac" class="col s6"><br>
			<label for="">Tipo Animal</label>
			<select name="tipoanimal" id="">
				<option value="0">Todos</option>
				<?php foreach($tiposAni as $tipoani){ ?>
					<option value="<?=$tipoani['id_tipo']?>"><?= $tipoani['nombre']?></option>
				<?php } ?>
			</select>
			<label for="">Raza</label>
			<select name="raza" id="">
				<option value="0">Todos</option>
				<?php foreach($Razas as $raza){ ?>
					<option value="<?=$raza['id_raza']?>"><?= $raza['nombre']?></option>
				<?php } ?>
			</select>
			<label for="">Tamaño</label>
			<select name="tamano" id="">
				<option value="0">Todos</option>
				<?php foreach($tamanos as $tamano){ ?>
					<option value="<?=$tamano['id_tamanio']?>"><?= $tamano['nombre']?></option>
				<?php } ?>
			</select>
			<label for="">Albergue</label>
			<select name="albergue" id="">
				<option value="0">Todos</option>
				<?php foreach($albergues as $albergue){ ?>
					<option value="<?=$albergue['id_albergue']?>"><?= $albergue['nombre']?></option>
				<?php } ?>
			</select>
			<label for="">Desde</label>
			<input type="date" value="<?= date('Y-m-d'); ?>" name="Desde" class="col s6"> 
			<br>
			<label for="">Hasta</label>
			<br>
			<input type="date" value="<?= date('Y-m-d'); ?>" name="Hasta" class="col s6">
			<select name="estatus" class="col s6">
				<option value="0">Todos</option>
				<option value="1">No adoptados</option>
				<option value="3">Adoptados</option>
			</select>
			<button name="Reporte" value="Peludos">Generar Reporte</button>
		</form>
	</div>

    <div id="Veterinarios" class="col s12">
		<form action="<?=BASE_URL?>report/Bitacora_Veterinarios" target="_blank" method="POST">
			<label>Veterinarios</label><br>
				<label for="">Nombre</label>
				<input type="text" name="nombre">
				<label for="">Admin que lo Registro</label>
				<input type="text" name="admin">
				<label>Visibilidad veterinarios</label>
			<select name="Visible">
					<option value="3">Todos</option>
					<option value="1">Visibles</option>
					<option value="0">Ocultos</option>
			</select>
				<button name="Reporte" value="Veterinarios">Generar Reporte</button>
		</form>
	</div>

    <div id="Usuarios" class="col s12">
	<form action="<?=BASE_URL?>report/Bitacora_Usuarios" target="_blank" method="POST">
			<label>Usuarios</label><br>
			<label for="">Cedula</label>
			<input name="cedula">
			<label for="">Nombre</label>
			<input name="nombre">
			<label>Buscar por Rol</label>
			<select name="busquedaRol">
				<option value="0">Todos</option>
			<?php foreach($roles as $rol){ ?>
				<option value="<?= $rol['id_rol']?>"><?= $rol['nombre']?></option>
			<?php } ?>
			</select>
			<br>
			<label>Buscar por Activo</label>
			<select name="busquedaAct">
				<option value="2">Todos</option>
				<option value="1">Activos</option>
				<option value="0">Bloqueados</option>
			</select>
				
			<button name="Reporte" value="Usuarios">Generar Reporte</button>
		</form>
	</div>

	<div id="General" class="col s12">
		<form action="<?=BASE_URL?>report/Bitacora_General" target="_blank" method="POST">
			<label>Bitacoras</label><br>
				<label for="">Usuario Acciones</label>
				<input type="text" name="usuario">
				<label for="">Modulo Afectado</label>
				<input type="text" name="modulo">
				<label for="">Accion Realizada</label>
				<input type="text" name="accion">
				<label>Visibilidad veterinarios</label>
				<label for="">Desde</label>
				<input type="date" value="<?= date('Y-m-d'); ?>" name="Desde" class="col s6"> 
				<br>
				<label for="">Hasta</label>
				<br>
				<input type="date" value="<?= date('Y-m-d'); ?>" name="Hasta" class="col s6">
				<button name="Reporte" value="Bitacora">Generar Reporte</button>
		</form>
	</div>

    <div id="Albergues" class="col s12">
		<form action="<?=BASE_URL?>report/Bitacora_Albergues" target="_blank" method="POST">
			<label>Albergues</label><br>
			<label for="">Nombre</label>
			<input type="text" name="nombre">
			<br>
			<label>Fundacion propietario</label>
			<input type="text" name="cedulaUser" id="">
			<div id="fecha">
			<select name="Activo" id="">
				<option value="2">Todos</option>
				<option value="1">Activo</option>
				<option value="0">Inactivo</option>
			</select>
			<button name="Reporte" value="Albergues">Generar Reporte</button>
		</form>
	</div>
	
	
  </div>