<?php

echo "Pagina para la toma de decision acerca de que tipo de reporte se quiere presentar";

?>
<!--
	Ahora modificar y que sean especificos osea con and en lugar de or y un catalogo de fundaciones
	en el usuario normal 
-->
<!--Podrias hacer que los reportes salgan en una ventana nueva para no tener que salir del sistema-->
<div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s2"><a class="active" href="#Animales">Animales</a></li>
        <li class="tab col s2"><a href="#Veterinarios">Veterinarios</a></li>
        <li class="tab col s2"><a href="#Usuarios">Usuarios</a></li>
        <li class="tab col s2"><a href="#Movimientos">Inicios de Sesión</a></li>
        <li class="tab col s2"><a href="#Bitacora">Bitacora</a></li>
      </ul>
    </div>
<!--$data['Razas'] =  $objAdmin->listaRazas('', 1, 10000);
        $data['tamanos'] = $objAdmin->consultaTamanoAnimal();
        $data['albergues'] = $objAdmin->consultaAlbergues();//id_albergue, nombre
        $data['tiposAni'] = $objSess->consultaTipoAnimal();-->
    <div id="Animales" class="col s12">
	<form action="<?=BASE_URL?>report/Bitacora_Animales" target="_blank" method="POST">
			<label>Animales</label><br>
			<label for="">Nombre</label>
			<input type="text" name="NombreAnimal" class="col s6">
			<label for="">Año de Nacimiento</label>
			<input name="Ano_nac" class="col s6"><br>
			<label for="">Tipo Animal</label>
			<select name="tipoanimal" id="">
				<option value="0">Todos</option>
				<?php foreach($tiposAni as $tipoani){ ?>
					<option value="<?=$tipoani['id_tipo']?>"><?= $tipoani['nombre']?></option>
				<?php } ?>
			</select>
			<label for="">Raza</label>
			<select name="raza" id="">
				<option value="0">Todos</option>
				<?php foreach($Razas as $raza){ ?>
					<option value="<?=$raza['id_raza']?>"><?= $raza['nombre']?></option>
				<?php } ?>
			</select>
			<label for="">Tamaño</label>
			<select name="tamano" id="">
				<option value="0">Todos</option>
				<?php foreach($tamanos as $tamano){ ?>
					<option value="<?=$tamano['id_tamanio']?>"><?= $tamano['nombre']?></option>
				<?php } ?>
			</select>
			<label for="">Albergue</label>
			<select name="albergue" id="">
				<option value="0">Todos</option>
				<?php foreach($albergues as $albergue){ ?>
					<option value="<?=$albergue['id_albergue']?>"><?= $albergue['nombre']?></option>
				<?php } ?>
			</select>
			<label for="">Desde</label>
			<input type="date" value="<?= date('Y-m-d'); ?>" name="Desde" class="col s6"> 
			<br>
			<label for="">Hasta</label>
			<br>
			<input type="date" value="<?= date('Y-m-d'); ?>" name="Hasta" class="col s6">
			<select name="estatus" class="col s6">
				<option value="0">Todos</option>
				<option value="1">No adoptados</option>
				<option value="3">Adoptados</option>
			</select>
			<button name="Reporte" value="Animales">Generar Reporte</button>
		</form>
	</div>

    <div id="Veterinarios" class="col s12">
	<form action="<?=BASE_URL?>report/Bitacora_Veterinarios" target="_blank" method="POST">
		<label>Veterinarios</label>
		<select name="Columna">
				<option value="0">ID Veterinario</option>
				<option value="1">Nombre</option>
				<option value="2">Visibilidad</option>
				<option value="3">Quien lo Registro</option>
			</select>
			<input name="Filtro"></input>
			<label>Visibilidad veterinarios</label>
		<select name="Visible">
				<option value="3">Todos</option>
				<option value="1">Visibles</option>
				<option value="0">Ocultos</option>
		</select>
			<button name="Reporte" value="Veterinarios">Generar Reporte</button>
	</form>
	</div>

    <div id="Usuarios" class="col s12">
	<form action="<?=BASE_URL?>report/Bitacora_Usuarios" target="_blank" method="POST">
			<label>Usuarios</label>
			<select name="Columna">
				<option value="0">Cedula</option>
				<option value="1">Nombre</option>
				<option value="2">Rol</option>
				<option value="3">Activo</option>
			</select>

			<input name="Filtro"></input>
			<label>Buscar por Rol</label>
			<select name="busquedaRol">
				<option value="0">Todos</option>
			<?php foreach($roles as $rol){ ?>
				<option value="<?= $rol['id_rol']?>"><?= $rol['nombre']?></option>
			<?php } ?>
			</select>
			<br>
			<label>Buscar por Activo</label>
			<select name="busquedaAct">
				<option value="2">Todos</option>
				<option value="1">Activos</option>
				<option value="0">Bloqueados</option>
			</select>
				
			<button name="Reporte" value="Usuarios">Generar Reporte</button>
		</form>
	</div>

    <div id="Movimientos" class="col s12">
	<form action="<?=BASE_URL?>report/Bitacora_Movimientos" target="_blank" method="POST">
		<label>Movimientos</label>
		<select name="Columna">
				<option value="0">ID Bitacora</option>
				<option value="1">Usuario Accion</option>
				<option value="2">Modulo afectado</option>
				<option value="3">Accion Realizada</option>
				<option value="4">Fecha Accion</option>
			</select>
			<br>
			<label>Busqueda</label>
			<input name="Filtro"></input>
			<br>
			<label>Acciones realizadas</label>
			<select name="accion">
				<option value="Todos">Todos</option>
				<option value="Logueandose">Iniciar sesión</option>
				<option value="Cerrar Sesion">Cerrar Sesión</option>
			</select>
			<div id="fecha">
			<label for="">Desde</label>
			<input type="date" value="<?= date('Y-m-d'); ?>" name="Desde" class="col s6"> 
			<br>
			<label for="">Hasta</label>
			<br>
			<input type="date" value="<?= date('Y-m-d'); ?>" name="Hasta" class="col s6">
			</div>
			<button name="Reporte" value="Movimientos">Generar Reporte</button>
		</form>
	</div>
	
	<div id="Bitacora" class="col s12">
	<form action="<?=BASE_URL?>report/Bitacora_General" target="_blank" method="POST">
		<label>Bitacora</label>
		<select name="Columna">
				<option value="0">ID Bitacora</option>
				<option value="1">Usuario Accion</option>
				<option value="2">Modulo afectado</option>
				<option value="3">Accion Realizada</option>
				<option value="4">Fecha Accion</option>
			</select>
			<input name="Filtro"></input>
			<div id="fecha">
			<label for="">Desde</label>
			<input type="date" value="<?= date('Y-m-d'); ?>" name="Desde" class="col s6"> 
			<br>
			<label for="">Hasta</label>
			<br>
			<input type="date" value="<?= date('Y-m-d'); ?>" name="Hasta" class="col s6">
			</div>
			<br>
			<label for="">Accion</label>
			<select name="acciones">
				<option value="Todos">Todos</option>
				<option value="INSERT">Insercion</option>
				<option value="UPDATE">Actualizacion</option>
				<option value="Logueandose">Login</option>
				<option value="Cerrar Sesion">Cerrar Sesion</option>
			</select>
			<button name="Reporte" value="Bitacora">Generar Reporte</button>
		</form>
	</div>

  </div>
  
  
  
 