<?php
$identificador = isset($tAnimal[0]['id_tipo'])? $tAnimal[0]['id_tipo']: "";
$nombre = isset($tAnimal[0]['nombre'])? $tAnimal[0]['nombre']: "";
?>
<table class="highlight centered">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Nombre</th>
        </tr>
    </thead>
    <tbody>
    <?php 
    $tamanio = count($dataTipos);
    for ($i = 0; $i < $tamanio; $i++){ ?>
        <tr>
            <td><?= $dataTipos[$i]['id_tipo'] ?></td>
            <td><?=$dataTipos[$i]['nombre'] ?></td>
            <td>
                <form action="<?=BASE_URL?>admin/tipoAnimal" method="POST">
                    <input type="hidden" name="modificacion" value="<?=$dataTipos[$i]['id_tipo'] ?>">
                    <button name="accion" value="Modificar">Modificar</button>
                </form>
            </td>
            </tr>
           <?php
        }
        ?>
        </tbody>
    </table>
    <div class="card text-center">
    <form action="<?= BASE_URL?>admin/agregaTipoanimal" method="POST">
        <label for="">Este es el formulario para registrar tipos de animal</label>
        <br>
        <label for="">ID <?=$identificador?></label>
        <input type="hidden" name="identificador" value="<?=$identificador?>">
        <br>
        <label for="">Nombre</label>
        <input type="text" name="nombreTipo" value="<?= $nombre?>">
        <br>
        <button name="accion" value="<?php if(isset($_POST['accion'])=="Modificar"){ echo "Modificar"; } else {echo"Agregar";} ?>">Aceptar</button>
    </form>
    </div>
