<div class="row" style="padding-top: 5%; padding-bottom: 5%;">
    <div class="col s10 login-card white black-text offset-s1">
        <div class="card-panel col s12 indigo white-text center" style="border-radius: 10px; padding-bottom: 20px;">
            <h3>Gestión de Tipos de Animales</h3>

            <?php
            $identificador = isset($tAnimal[0]['id_tipo'])? $tAnimal[0]['id_tipo']: "";
            $nombre = isset($tAnimal[0]['nombre'])? $tAnimal[0]['nombre']: "";
            $total_paginas = ceil($totalregistro / $por_pagina);
            ?>


            <form action="<?= BASE_URL?>admin/agregaTipoanimal" method="POST">
            <div class="text-center col s12">
                <div class="center-align" for="filtro">
                    <?php if(isset($_POST['accion'])=="Modificar"){ ?>
                        <h5 class="light">Modificar tipo de animal</h5> <?php } else { ?>
                        <h5 class="light">Agregar tipo de animal</h5> <?php } ?>
                </div>
                <div class="card col s8 offset-s2"  style="border-radius: 10px; padding-bottom: 20px;">
                    <div class="input-field tooltipped col s12" data-position="bottom" data-tooltip="Nombre del tipo de animal">
                        <label class="black-text" for="">Nombre</label>
                        <span class="helper-text right">ID: <?=$identificador?></span>
                        <input maxlength="50" pattern= "[A-Z,a-z ^()/><\][\\\x22,;|]{1,50}" title="50 caracteres max. - Sin números o signos" required  class="validate" type="text" name="nombreTipo" value="<?= $nombre?>">
                        <span class="helper-text">50 caracteres max. - Sin números o signos</span>
                        <input type="hidden" name="identificador" value="<?=$identificador?>">
                    </div>
                    <div class="col s12">
                    <?php if(isset($_POST['accion']) == "Modificar") { ?>
                        <a href="<?= BASE_URL;?>admin/tipoAnimal">
                            <input class="btn indigo" type="button" value="Volver">
                        </a> 
                    <?php } ?>
                        <button class="tooltipped btn indigo"  data-position="bottom" data-tooltip="Registrar" name="accion" value="<?php if(isset($_POST['accion'])=="Modificar"){ echo "Modificar"; } else {echo"Agregar";} ?>"><i class="large material-icons">send</i></button>
                    </div>
                </div>
            </div>
            </form>

        </div>

        <?php getDashboard("admin") ?>

        <div class="col s10">
    <table class="centered">
        <thead class="card indigo white-text">
        <tr>
            <th scope="col">N°</th>
            <th scope="col">Nombre</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
    <?php 
    $tamanio = count($dataTipos);
    for ($i = 0; $i < $tamanio; $i++){ ?>
        <tr>
            <td><?= $dataTipos[$i]['id_tipo'] ?></td>
            <td><?=$dataTipos[$i]['nombre'] ?></td>
            <td>
                <form action="<?=BASE_URL?>admin/tipoAnimal" method="POST">
                <input type="hidden" name="modificacion" value="<?=$dataTipos[$i]['id_tipo'] ?>">
                    <button class="btn tooltipped blue" data-position="bottom" data-tooltip="Modificar Tipo de Animal" name="accion" value="Modificar">
                        <i class="large material-icons">edit</i>
                    </button>
                </form>
            </td>
            </tr>
           <?php
        }
        ?>
        </tbody>
    </table>
    <ul class="pagination center">
        <?php if($pagina != 1){ ?>
            <li class="waves-effect blue-text"><a href="<?=BASE_URL?>admin/tipoAnimal?pagina=1"><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="waves-effect"><a href="<?=BASE_URL?>admin/tipoAnimal?pagina=<?=$pagina - 1?>"><i class="material-icons">chevron_left</i></a></li>
        <?php } else { ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i></a></li>
        <?php } ?>
        <?php for($i = 1; $i <= $total_paginas; $i++){ 
            if ($i == $pagina){ ?>
                <li class="active indigo"><a href="<?=BASE_URL?>admin/tipoAnimal?pagina=<?=$i?>"><?=$i?></li>
            <?php } else { ?>
                <li class="waves-effect"><a href="<?=BASE_URL?>admin/tipoAnimal?pagina=<?=$i?>"><?=$i?></a></li>
            <?php } } ?>
        <?php if($pagina != $total_paginas){ ?>
            <li class="waves-effect"><a href="<?=BASE_URL?>admin/tipoAnimal?pagina=<?=$pagina + 1?>"><i class="material-icons">chevron_right</i></a></li>
            <li class="waves-effect"><a href="<?=BASE_URL?>admin/tipoAnimal?pagina=<?=$total_paginas?>"><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
        <?php } else { ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
        <?php } ?>
    </ul>
    </div>
    </div>
</div>