<?php
$idAlbergue = isset($albergue[0]['id_albergue'])? $albergue[0]['id_albergue']:"";
$nombre =  isset($albergue[0]['nombre'])? $albergue[0]['nombre']:"";
$direccion = isset($albergue[0]['direccion'])? $albergue[0]['direccion']:"";
$usuario =  isset($albergue[0]['cedula_usuario'])? $albergue[0]['cedula_usuario']:"";
$activo =  isset($albergue[0]['activo'])? $albergue[0]['activo']:"";

?>

<div class="card text-center">
      <div class="card-body">
        <h4 class="card-title">Title</h4>
        <p class="card-text">Pagina para registrar/Modificar Albergues</p>
        <form action="<?=BASE_URL;?>fundacion/registraFundacion" method="post">
        <input type="hidden" name="identificador" value="<?= $idAlbergue?>">
        <label for="">Nombre Albergue</label>
        <input type="text" name="nombre" value="<?=$nombre?>" required >
        <label for="">Direccion</label>
        <input type="text" name="direccion" value="<?= $direccion?>"required><br>
        <label for="">Ced_usuario</label>
        <select name="cedula_user" id="">
          <option value="0">Seleccionar</option>
          <!--=============================================
            Este es el usuario de fundacion al que se le 
            añadira el albergue nuevo
          ==============================================-->
        <?php 
          foreach ($userfund as $key) {?>
          <option <?php if($usuario == $key['cedula']){ echo"selected"; } ?> value="<?= $key['cedula']; ?>"><?= $key['nombre']; ?></option>
          <?php
          }
        ?>
        </select>
        <br>
        <?php
          if(isset($_POST['accion'])=="Modificar"){?>
            <label for="">Activo</label>
            <input type="text" value="<?= $activo;?>" name="activo">
            <?php
          }
        ?>
        <button name="accion" value="<?php if(isset($_POST['accion'])=="Modificar"){ echo "Modificar"; } else {echo"Agregar";} ?>">Aceptar</button>
        </form>
      </div>
    </div>