<?php
$id_animal = (isset($animales[0]['id_animal']))? $animales[0]['id_animal'] :"";
$tipoanimalSelecc = (isset($animales[0]['id_tipo_animal']))? $animales[0]['id_tipo_animal'] :"";
$Nombre = (isset($animales[0]['nombre']))? $animales[0]['nombre'] :"";
$anio_nac =(isset($animales[0]['anio_nac']))? $animales[0]['anio_nac'] :"";
$img = (isset($animales[0]['img']))? $animales[0]['img'] :"";
$Descripcion = (isset($animales[0]['descripcion']))? $animales[0]['descripcion'] :"";
$Raza = (isset($animales[0]['raza_id']))? $animales[0]['raza_id'] :"";
$tamanio_mod = (isset($animales[0]['tamanio_id']))? $animales[0]['tamanio_id'] :"";
$Albergue = (isset($animales[0]['albergue_id']))? $animales[0]['albergue_id'] :"";
$visible = (isset($animales[0]['visible']))? $animales[0]['visible']:"";
?>
<div class="card text-center">
<label for="">Tipo animal</label>
<form action="<?= BASE_URL?>admin/agregaAnimales" method="POST">
        <select name="tipoanimal" id="tipo_animal">
          <option value="0">Selecciona</option>
          <!--=============================================
            Este es el usuario de fundacion al que se le 
            añadira el albergue nuevo
          ==============================================-->
        <?php 
          foreach ($tipoanimal as $key) {?>
          <option <?php if($tipoanimalSelecc == $key['id_tipo']){ echo"selected"; } ?> value="<?= $key['id_tipo']; ?>"><?= $key['nombre']; ?></option>
          <?php
          }
        ?>
        </select>
        <button <?php if($tipoanimalSelecc != ""){ echo "disabled";} ?> >Seleccionar Animal</button>
        </form>
        </div>
<div class="card text-center">
      <div class="card-body">
        <h4 class="card-title">Title</h4>
        <p class="card-text">
          Pagina para registrar animales Desde Admin.
          Estos inputs se mantendran debido a que el admin no tiene albergue
        </p>
        <form action="<?=BASE_URL;?>admin/agregaAnimal" method="post" enctype="multipart/form-data">
        <input type="hidden" value="<?= $id_animal;?>" name="id_animal">
        <?php if($id_animal != ""){ ?><label for="">Animal Modificando: <?=$id_animal?></label><?php }?>
        <label for="">Nombre Animal</label>
        <input type="text" value="<?= $Nombre;?>" name="nombre" >
        <label for="">Año de nacimiento</label>
        <input type="text" value="<?= $anio_nac?>" name="fecha"><br>
        <label for="">Imagen Original: <?=$img?></label><br>
        <label for="">Imagen</label>
        <input type="hidden" value="<?=$img?>" name="imgmodificar">
        <input type="file" name="img"><br><!--No hay forma creo ahora mismo de poner lo q recibo de img-->
        <label for="">Descripcion</label>
        <input type="text" value="<?= $Descripcion?>" name="descrip" >
        
        <br>
        <?php if(isset($raza)){ ?>
        <label for="">Raza</label>
        <label for="">Usted Selecciono (aca escribir que animal seleccionaste)</label>
        <select name="raza" id="">
          <option value="0">Selecciona</option>
          <!--=============================================
            Este es el usuario de fundacion al que se le 
            añadira el albergue nuevo
          ==============================================-->
        <?php 
          foreach ($raza as $key) {?>
          <option <?php if($Raza == $key['id_raza']){ echo"selected"; } ?> value="<?= $key['id_raza']; ?>"><?= $key['nombre']; ?></option>
          <?php
          }
        ?>
        </select>
        <?php } else {
          echo "
          <select name='raza'>
            <option value='0'>Seleccione un Animal</option>
          </select>";
          }?>
        <br>
        <label for="">Tamaño</label>
        <select name="tamano" id="">
          <option value="0">Selecciona</option>
          <!--=============================================
            Este es el usuario de fundacion al que se le 
            añadira el albergue nuevo
          ==============================================-->
        <?php 
          foreach ($tamano as $key) {?>
          <option <?php if($tamanio_mod == $key['id_tamanio']){ echo"selected"; } ?> value="<?= $key['id_tamanio']; ?>"><?= $key['nombre']; ?></option>
          <?php
          }
        ?>
        </select>
        <br>
        <label for="">Albergue</label>
        <select name="albergue" id="">
          <option value="0">Selecciona</option>
          <!--=============================================
            Este es el usuario de fundacion al que se le 
            añadira el albergue nuevo
          ==============================================-->
        <?php 
          foreach ($albergues as $key) {
           ?>
          <option <?php if($Albergue == $key['id_albergue']){ echo"selected"; } ?> value="<?= $key['id_albergue']; ?>"><?= $key['nombre']; ?></option>
          <?php

          }
        ?>
        </select>
        <br>
        <?php
          if(isset($_POST['accion'])=="Modificar"){?>
          <label for="">Activo</label>
          <input type="text" name="visible" value="<?= $visible?>">
        <?php
          }
        ?>

        <!--No se mostrara si la adopcion se esta procesando porque esta no es su ventana-->
        <button name="accion" value="<?php if(isset($_POST['accion'])=="Modificar"){ echo "Modificar"; } else {echo"Agregar";} ?>">Aceptar</button>
        </form>
      </div>
    </div>
