<div class="row" style="padding-top: 5%; padding-bottom: 5%;">
<div class="col s10 login-card white black-text offset-s1">

  <?php
  $id_animal = (isset($animales[0]['id_animal']))? $animales[0]['id_animal'] :"";
  $tipoanimalSelecc = (isset($animales[0]['id_tipo_animal']))? $animales[0]['id_tipo_animal'] :"";
  $Nombre = (isset($animales[0]['nombre']))? $animales[0]['nombre'] :"";
  $anio_nac =(isset($animales[0]['anio_nac']))? $animales[0]['anio_nac'] :"";
  $img = (isset($animales[0]['img']))? $animales[0]['img'] :"";
  $Descripcion = (isset($animales[0]['descripcion']))? $animales[0]['descripcion'] :"";
  $Raza = (isset($animales[0]['raza_id']))? $animales[0]['raza_id'] :"";
  $tamanio_mod = (isset($animales[0]['tamanio_id']))? $animales[0]['tamanio_id'] :"";
  $Albergue = (isset($animales[0]['albergue_id']))? $animales[0]['albergue_id'] :"";
  $visible = (isset($animales[0]['visible']))? $animales[0]['visible']:"";
  ?>

<div class="card-panel col s12 indigo white-text center" style="border-radius: 10px; padding-bottom: 20px;"> <!--BANNER INICIO-->
	<h3>Registro de Mascotas</h3>
</div>

<div class="card-title center-align">
  <span>Paso N°1 - Elige el tipo de animal a registrar</span>
</div>

<div class="input-field col s12">
  <form action="<?= BASE_URL?>admin/agregaAnimales" method="POST">
    <i class="indigo-text material-icons prefix">image</i>
    <select name="tipoanimal" id="tipo_animal">
    <option value="0" disabled selected>Selecciona:</option>
      <?php foreach ($tipoanimal as $key) {?>
        <option <?php if($tipoanimalSelecc == $key['id_tipo']){ echo"selected"; } ?> value="<?= $key['id_tipo']; ?>"><?= $key['nombre']; ?></option>
      <?php } ?>
    </select>
    <span class="col s12 center helper-text" style="padding-bottom: 10px;">Una vez seleccionado, se mostrara el formulario de registro.</span>

    <div class="input-field">
			<button class="btn col s2 offset-s5 indigo white-text" <?php if($tipoanimalSelecc != ""){ echo "disabled";} ?> >Seleccionar Animal</button>		</div>

  </form>
</div>

<?php if(isset($raza)){ ?>

<div class="card-title center-align">
  <span>Paso N°2 - Completa los datos de registro</span>
</div>

<div class="col s12">
  <form action="<?=BASE_URL;?>admin/agregaAnimal" method="post" enctype="multipart/form-data">
      <input type="hidden" value="<?= $id_animal;?>" name="id_animal">

      <div class="input-field col s3">
        <i class="indigo-text material-icons prefix">pets</i>
        <label for="">Nombre de Mascota</label>
        <input maxlength="50" pattern= "[A-Z,a-z ^()/><\][\\\x22,;|]{1,50}" title="Sin números o signos." class="validate" type="text" value="<?= $Nombre;?>" name="nombre" >
      	<span class="helper-text">Sin números o signos.</span>	
      </div>

      <div class="input-field col s3">
        <i class="indigo-text material-icons prefix">date_range</i>
        <label for="">Año de nacimiento</label>
        <input maxlength="5" pattern= "[0-9 ^()/><\][\\\x22,;|]{1,5}" title="Solo números." class="validate" type="number" min="<?= date('Y')-30;?>" max="<?= date('Y'); ?>" value="<?= $anio_nac?>" name="fecha">
        <span class="helper-text">Solo números.</span>	
      </div>

      <div class="input-field col s2">
        <i class="indigo-text material-icons prefix">group_work</i>
        <?php if(isset($raza)){ ?>
          <select name="raza" id="">
            <option value="0" disabled selected>Selecciona:</option>
            <?php foreach ($raza as $key) { ?>
            <option <?php if($Raza == $key['id_raza']){ echo"selected"; } ?> value="<?= $key['id_raza']; ?>"><?= $key['nombre']; ?></option>
            <?php } ?>
          </select>
          <label for="">Raza</label>
          <span class="helper-text"></span>	
        <?php } else { echo " <select name='raza'> <option value='0'>No hay un tipo de animal seleccionado</option> </select>"; }?>
      </div>  

      <div class="input-field col s2">
        <i class="indigo-text material-icons prefix">format_size</i>
        <select name="tamano" id="">
          <option value="0" disabled selected>Selecciona:</option>
          <?php foreach ($tamano as $key) { ?>
          <option <?php if($tamanio_mod == $key['id_tamanio']){ echo"selected"; } ?> value="<?= $key['id_tamanio']; ?>"><?= $key['nombre']; ?></option>
          <?php } ?>
        </select>
        <label for="">Tamaño</label>
        <span class="helper-text"></span>	
      </div>

      <div class="input-field col s2">
        <i class="indigo-text material-icons prefix">home</i>
        <select name="albergue" id="">
          <option value="0" disabled selected>Selecciona:</option>
          <?php foreach ($albergues as $key) { ?>
          <option <?php if($Albergue == $key['id_albergue']){ echo"selected"; } ?> value="<?= $key['id_albergue']; ?>"><?= $key['nombre']; ?></option>
          <?php } ?>
        </select>
        <label for="">Albergue</label>
        <span class="helper-text"> </span>	
      </div>

      <div class="input-field col s6">
        <i class="indigo-text material-icons prefix">description</i>
        <label for="">Descripcion</label>
        <input maxlength="100" pattern= "[A-Z,a-z ^()/><\][\\\x22,;|]{1,50}" title="Sin números o signos." class="validate" type="text" value="<?= $Descripcion?>" name="descrip" >
      	<span class="helper-text">Sin números o signos.</span>	
      </div>  

      <div class="file-field input-field col s6">
        <div class="btn indigo">
          <span>Buscar...</span>
          <input type="file" name="img">
        </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text">
        </div>
      </div>

      <?php if(isset($_POST['accion'])=="Modificar") { ?>
      <input type="hidden" name="visible" value="<?= $visible?>">
      <?php } ?>

      <!--Este input es importante porque se envia a modificar para comparar si la imagen se esta cambiando-->
      <input type="hidden" value="<?=$img?>" name="imgmodificar">
      <!--No se mostrara si la adopcion se esta procesando porque esta no es su ventana-->

      <div class="input-field col s12">
      <a href="<?= BASE_URL;?>admin/animales"><input class="btn indigo col s2" type="button" value="Volver"></a>
      <button class="col s2 offset-s8 btn indigo" name="accion" value="<?php if(isset($_POST['accion'])=="Modificar"){ echo "Modificar"; } else {echo"Agregar";} ?>">Aceptar</button>
      </div>
      
  </form>
</div>

<?php } ?>

</div>
</div>
