<div class="row" style="padding-top: 5%; padding-bottom: 5%;">
<div class="col s10 login-card white black-text offset-s1">

<?php
if (isset($_GET['error'])){
  echo "<h1>". $_GET['error'] ."</h1>";
}
$cedula = isset($usuario[0]['cedula'])? $usuario[0]['cedula']:"";
$Nombre =isset($usuario[0]['nombre'])? $usuario[0]['nombre']:"";
$Rol =isset($usuario[0]['rol_id'])? $usuario[0]['rol_id']:"";
$Direccion = isset($usuario[0]['direccion'])? $usuario[0]['direccion']:"";
$contra =isset($usuario[0]['contrasenia'])? $usuario[0]['contrasenia']:"";
$tlf =isset($usuario[0]['telefono'])? $usuario[0]['telefono']:"";
$activo = isset($usuario[0]['activo'])? $usuario[0]['activo']:"";
$detalle = isset($usuario[0]['detalles'])? $usuario[0]['detalles']:"";
?>

<div class="card-panel col s12 indigo white-text center" style="border-radius: 10px; padding-bottom: 20px;"> <!--BANNER INICIO-->
	<h3>Registro de Usuarios</h3>
</div>

<div class="col s12">
  <form action="<?= BASE_URL;?>admin/registraUsuario" method="post">

  <div class="input-field col s6">
    <i class="indigo-text material-icons prefix">account_circle</i>
    <label for="nombre">Nombre</label>
    <input type="text" name="nombre" value="<?=$Nombre?>" maxlength="50" pattern= "[A-Z,a-z ^()/><\][\\\x22,;|]{1,50}" title="Sin números o signos." class="validate" required><br>
    <span class="helper-text">Sin números o signos.</span>	
  </div>  

  <div class="input-field col s6">
    <i class="indigo-text material-icons prefix">https</i>
    <label for="contrasenia">Contraseña</label>
    <input class="validate" type="password" name="contrasenia" value="<?= $contra?>" maxlength="20" pattern="[a-z,0-9  ^()/><\][\\\x22,;|]{8,20}" title="Entre 8 y 20 caracteres - Sin signos." required>
    <span class="helper-text">Entre 8 y 20 caracteres - Sin signos.</span>
  </div>

  <div class="input-field col s4">
    <i class="indigo-text material-icons prefix">contacts</i>
    <label for="">Nro° de Cedula/RIF</label>
    <input class="validate" type="text" name="cedula" value="<?=$cedula?>" maxlength="8" pattern= "[0-9 ^()/><\][\\\x22,;|]{7,8}" type="text" title="Solo números e identificaciones validas." min="1000000" max="40000000" required>
    <span class="helper-text">Solo números e identificaciones validas.</span>
  </div>

  <div class="input-field col s4">
    <i class="indigo-text material-icons prefix">phone_android</i>
    <label for="telefono">Telefono</label>
    <input class="validate" type="tel" name="telefono" value="<?= $tlf?>" maxlength="11" pattern= "[0-9 ^()/><\][\\\x22,;|]{11}" title="11 caracteres requeridos - Sin letras o signos"  required>
    <span class="helper-text">11 caracteres requeridos - Sin letras o signos.</span>
  </div>

  <div class="input-field col s4">
    <i class="indigo-text material-icons prefix">business_center</i>
    <select name="rol" id="">
    <option value="0" disabled selected>Selecciona:</option>
    <?php foreach ($dataRoles as $key) {?>
    <option <?php if($Rol == $key['id_rol']){ echo"selected"; } ?> value="<?= $key['id_rol']; ?>"><?= $key['nombre']; ?></option>
    <?php } ?>
    </select>
    <label for="rol">Rol</label>
    <span class="helper-text">Fijate bien que rol asignas.</span>
  </div>

  <div class="input-field col s6">
    <i class="indigo-text material-icons prefix">home</i>
    <label for="direccion">Dirección</label>
    <input class="validate" type="text" name="direccion" value="<?=$Direccion?>" maxlength="255" pattern="{5,255}" title="Debe contener un minimo de 5 caracteres y un maximo 255 caracteres." required>
    <span class="helper-text">5 caracteres requeridos como minimo.</span>
  </div>

  <div class="input-field col s6">
    <i class="indigo-text material-icons prefix">description</i>
    <label for="detalle">Detalles</label>
    <input class="validate" type="text" name="detalle" value="<?= $detalle?>" maxlength="30" pattern="{1,30}" title="Debe contener un caracter minimo y un maximo 30 caracteres." required>
    <span class="helper-text"></span>
  </div>

  <?php if($activo != ""){ ?>
    <input class="validate"  type="hidden" name="activo" value="<?= $activo?>">
  <?php }?>

  <div class="input-field col s12">
    <a href="<?= BASE_URL;?>admin/mostrarData"><input class="btn indigo col s2" type="button" value="Volver"></a>
    <button class="col s2 offset-s8 btn indigo" name="<?php if(isset($_POST['accion'])=="Modificar"){ echo "Modificar"; } else {echo"Agregar";} ?>">Aceptar</button>
  </div>
         
  </form>
</div>

</div>
</div>
