<div class="row" style="padding-top: 5%; padding-bottom: 5%;">
<div class="col s10 white offset-s1">
<div class="row" style="padding-left: 15px; padding-right: 15px;">
    <div class="card  col s3 black-text transparent z-depth-0">
        <h3>Menu Principal</h3>
        <hr style="border-top: 8px solid; border-radius: 5px;">
        <ul>
        <li><a href="<?= BASE_URL;?>admin/tipoAnimal">Tipos de Animales</a></li>
          <li><a href="<?= BASE_URL;?>admin/razasAnimal">Razas de Animales</a></li>
          <li><a href="<?= BASE_URL;?>admin/agregaVeterinarios">Veterinarios</a></li>
          <li><a href="<?= BASE_URL;?>admin/animales">Peludos</a></li>
          <li><a href="<?= BASE_URL;?>admin/mostrarData">Usuarios</a></li>
          <li><a href="<?= BASE_URL;?>admin/albergues">Albergues</a></li>
          <li><a href="<?= BASE_URL;?>admin/adopciones">Adopciones</a></li>
          <li><a href="<?= BASE_URL;?>admin/Reportes">Reportes</a></li>
        </ul>
    </div>

<div class="card col s9 black-text transparent z-depth-0">
  <div class="card-title center-align"><h3>Registro de Usuarios</h3></div>
  <hr style="border-top: 8px solid; border-radius: 5px;">

<?php
if (isset($_GET['error'])){
  echo "<h1>". $_GET['error'] ."</h1>";
}
$cedula = isset($usuario[0]['cedula'])? $usuario[0]['cedula']:"";
$Nombre =isset($usuario[0]['nombre'])? $usuario[0]['nombre']:"";
$Rol =isset($usuario[0]['rol_id'])? $usuario[0]['rol_id']:"";
$Direccion = isset($usuario[0]['direccion'])? $usuario[0]['direccion']:"";
$contra =isset($usuario[0]['contrasenia'])? $usuario[0]['contrasenia']:"";
$tlf =isset($usuario[0]['telefono'])? $usuario[0]['telefono']:"";
$activo = isset($usuario[0]['activo'])? $usuario[0]['activo']:"";
$detalle = isset($usuario[0]['detalles'])? $usuario[0]['detalles']:"";
?>


      <div class="row">
        <form action="<?= BASE_URL;?>admin/registraUsuario" method="post">

          <div class="input-field col s6 tooltipped" data-position="top" data-tooltip="Nombre de la persona o fundación">
            <i class="indigo-text material-icons prefix">account_circle</i>
            <label for="nombre">Nombre</label>
            <input class="validate" type="text" name="nombre" value="<?=$Nombre?>" maxlength="30" pattern="[a-z,A-Z]{1,30}" title="No puede contener numeros, caracteres especiales o ser mayor a 30 caracteres." required><br>
            <span class="helper-text black-text">Ejemplo: Pedro Pérez/Fundamascotas</span>
          </div>
          
          <div class="input-field col s6 tooltipped" data-position="top" data-tooltip="Contraseña privada para inicio de sesión">
            <i class="indigo-text material-icons prefix">https</i>
            <label for="contrasenia">Contraseña</label>
            <input class="validate" type="password" name="contrasenia" value="<?= $contra?>" maxlength="20" pattern="[a-z,0-9]{8,20}" title="No puede contener caracteres especiales, ser menor a 8 o mayor a 20 caracteres." required>
            <span class="helper-text black-text">Longitud de 8 a 20 caracteres - Sin caracteres especiales</span>
          </div>

          <div class="input-field col s4 tooltipped" data-position="top" data-tooltip="Identificación de la persona o fundación">
            <i class="indigo-text material-icons prefix">contacts</i>
            <label for="">Nro° de Cedula/RIF</label>
            <input class="validate" type="text" name="cedula" value="<?=$cedula?>" maxlength="11" pattern="[0-9]{8,9}" title="Debe contener  8 o 9 numeros de identificación." required >
            <span class="helper-text black-text">Ejemplo: 123456789</span>
          </div>

          <div class="input-field col s4 tooltipped" data-position="top" data-tooltip="Contacto telefonico de la persona o fundación">
            <i class="indigo-text material-icons prefix">phone_android</i>
            <label for="telefono">Telefono</label>
            <input class="validate" type="tel" name="telefono" value="<?= $tlf?>" maxlength="12" pattern="[0-9]{11}" title="Debe empezar con el codigo del proveedor (0424/0412/0426/0251) seguido de 7 numeros." required>
            <span class="helper-text black-text">Ejemplo: 04127756455</span>
          </div>

          <div class="input-field col s4 tooltipped" data-position="top" data-tooltip="Permisos que tendra la persona o fundación">
            <i class="indigo-text material-icons prefix">business_center</i>
            <label for="rol">Rol</label>
            <select name="rol" id="">
              <option name="0" id="">Rol</option>
            <?php 
              foreach ($dataRoles as $key) {?>
              <option <?php if($Rol == $key['id_rol']){ echo"selected"; } ?> value="<?= $key['id_rol']; ?>"><?= $key['nombre']; ?></option>
              <?php
              }
            ?>
            </select>
            <span class="helper-text black-text">¡Fijate bien que rol asignas!</span>
          </div>

          <div class="input-field col s6 tooltipped" data-position="top" data-tooltip="Ubicación de la persona o fundación">
            <i class="indigo-text material-icons prefix">home</i>
            <label for="direccion">Dirección</label>
            <input class="validate" type="text" name="direccion" value="<?=$Direccion?>" maxlength="255" pattern="{5,255}" title="Debe contener un minimo de 5 caracteres y un maximo 255 caracteres." required>
            <span class="helper-text black-text">Ejemplo: Calle 01 con Carrera 12 (Minimo 5 caracteres)</span>
          </div>

          <div class="input-field col s6 tooltipped" data-position="top" data-tooltip="Comentario extra acerca de la persona o fundación">
            <i class="indigo-text material-icons prefix">description</i>
            <label for="detalle">Detalles</label>
            <input class="validate" type="text" name="detalle" value="<?= $detalle?>" maxlength="30" pattern="{1,30}" title="Debe contener un caracter minimo y un maximo 30 caracteres." required>
            <span class="helper-text black-text">Ejemplo: Cuidador Excepcional</span>
          </div>
          
          <?php if($activo != ""){ ?>

          <input class="validate"  type="hidden" name="activo" value="<?= $activo?>">
          
          <?php
          }
          ?>

          <a href="<?= BASE_URL;?>admin/mostrarData"><input class="btn indigo col s2" type="button" value="Volver"></a>
          <button class="col s2 offset-s8 btn indigo" name="<?php if(isset($_POST['accion'])=="Modificar"){ echo "Modificar"; } else {echo"Agregar";} ?>">Aceptar</button>
        </form>
          
          
      </div>
      
    </div>
</div>
</div>
</div>
