<div class="row" style="padding-top: 5%; padding-bottom: 5%;">
    <div class="col s10 login-card white black-text offset-s1">
        <div class="card-panel col s12 indigo white-text center" style="border-radius: 10px; padding-bottom: 20px;">
            <h3>Gestión de Veterinarios</h3>

            <?php 
            if (isset($error)){
                echo $error;
            }
            $identificador = isset($vtrModificar[0]['id_veterinario'])? $vtrModificar[0]['id_veterinario']: "";
            $nombre = isset($vtrModificar[0]['nombre'])? $vtrModificar[0]['nombre']: "";
            $telefono = isset($vtrModificar[0]['tlf'])? $vtrModificar[0]['tlf']: "";
            $direccion = isset($vtrModificar[0]['direccion'])? $vtrModificar[0]['direccion']: "";
            $img = isset($vtrModificar[0]['img'])? $vtrModificar[0]['img']: "";
            $visible = isset($vtrModificar[0]['visible'])? $vtrModificar[0]['visible']: "";

            $total_paginas = ceil($totalregistro / $por_pagina);
            ?>

<form action="<?=BASE_URL;?>admin/registraVeterinario" method="post" enctype="multipart/form-data">
<div class="text-center col s12">
<div class="center-align col s12" for="filtro">
        <?php if(isset($_POST['accion'])=="Modificar"){ ?>
            <h5 class="light"> Modificar al veterinario: Nro° <?=$identificador?> </h5>
        <?php } else { ?>
            <h5 class="light"> Registrar veterinarios</h5>
        <?php } ?>
    </div>
<div class="card col s8 offset-s2"  style="border-radius: 10px; padding-bottom: 20px;">
        <input type="hidden" name="vetIdentificador" value="<?= $identificador?>">

        <div class="input-field tooltipped col s6" data-position="top" data-tooltip="Nombre del veterinario">
        <i class="indigo-text material-icons prefix">person</i>
        <label for="">Nombre Veterinario</label>
        <input type="text" name="nombre" value="<?=$nombre?>">
        </div>

        <div class="input-field tooltipped col s6" data-position="top" data-tooltip="Nro° de telefono del veterinario">
        <i class="indigo-text material-icons prefix">phone</i>
        <label for="">Telefono</label>
        <input type="tel" name="telefono" value="<?=$telefono?>">
        </div>
        <input type="hidden" value="<?=$img?>" name="imgmodificar">
        <div class="input-field tooltipped col s6" data-position="top" data-tooltip="Dirección del consultorio del veterinario">
        <i class="indigo-text material-icons prefix">home</i>
        <label for="">Direccion</label >
        <input type="text" name="direccion" value="<?=$direccion?>">
        </div>

        <div class="file-field input-field tooltipped col s6" data-position="top" data-tooltip="Foto del veterinario">
            <div class="btn indigo">
                <span>Buscar..</span>
            <input type="file" name="img">
            </div>
            <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
            </div>
        </div>

        <input type="hidden" name="admin" value="<?=$id_user;?>">
        <?php 
        if ($visible != "") { ?>
        <input type="hidden" name="visible" value="<?=$visible?>">
        <?php } ?>
        <button class="tooltipped btn indigo col s2 offset-s5"  data-position="bottom" data-tooltip="Registrar" name="accion" value="<?php if(isset($_POST['accion'])=="Modificar"){ echo "Modificar"; } else {echo"Agregar";} ?>"><i class="large material-icons">send</i></button>
        </div>
        </div>
    </form>


        </div>

        <div class="col s2 black-text">
            <h4 class="card-panel indigo center white-text" style="border-radius: 10px;">Menú</h4>
            <ul class="card-panel indigo" style="padding-left: 15px; border-radius: 10px;">
                <li class="hover center"><a href="<?= BASE_URL;?>admin/tipoAnimal"><span class="white-text">Tipos de Animales</span></a></li>
                <li class="hover center"><a href="<?= BASE_URL;?>admin/razasAnimal"><span class="white-text">Razas de Animales</span></a></li>
                <li class="hover center"><a href="<?= BASE_URL;?>admin/agregaVeterinarios"><span class="white-text">Veterinarios</span></a></li>
                <li class="hover center"><a href="<?= BASE_URL;?>admin/animales"><span class="white-text">Peludos</span></a></li>
                <li class="hover center"><a href="<?= BASE_URL;?>admin/mostrarData"><span class="white-text">Usuarios</span></a></li>
                <li class="hover center"><a href="<?= BASE_URL;?>admin/albergues"><span class="white-text">Albergues</span></a></li>
                <li class="hover center"><a href="<?= BASE_URL;?>admin/adopciones"><span class="white-text">Adopciones</span></a></li>
                <li class="hover center"><a href="<?= BASE_URL;?>admin/Reportes"><span class="white-text">Reportes</span></a></li>
            </ul>
        </div>

        <div class="col s10">
<table class="centered">
        <thead class="card indigo white-text">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nombre</th>
                <th scope="col">Telefono</th>
                <th scope="col">Direccion</th>
                <th scope="col">Imagen</th>
                <th scope="col">Estado</th>
                <th scope="col">Registrado por</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
        <?php 
        
        $tamanio = count($Veterinarios);
        for ($i = 0; $i < $tamanio; $i++){ ?>
            <tr>
            <td><?= $Veterinarios[$i]['id_veterinario'] ?></td>
            <td><?= $Veterinarios[$i]['nombre'] ?></td>
            <td><?= $Veterinarios[$i]['tlf'] ?></td>
            <td><?= $Veterinarios[$i]['direccion'] ?></td>
            <td> 
                <img src='<?= URL_BASE . "img/veterinarios/".$Veterinarios[$i]['img'];?>' width='50' alt='Foto Veterinario'>
            </td>
            <td><?= $activo = $Veterinarios[$i]['visible'] !=1? "No visible": "Visible" ?> </td>
            <td><?= $Veterinarios[$i]['usuario_Rveterinario']  ?> </td>
            <td>
                <div class="col s12">
                    <div class="col s6">
                        <form action="<?=BASE_URL?>admin/agregaVeterinarios" method="POST">
                            <input type="hidden" name="modificacion" value="<?=$Veterinarios[$i]['id_veterinario'] ?>">
                            <button class="btn tooltipped blue" data-position="bottom" data-tooltip="Modificar Usuario" name="accion" value="Modificar">
                                <i class="large material-icons">edit</i>
                            </button>
                        </form>
                    </div>                    
                    <div class="col s6">
                        <form action="<?=BASE_URL?>admin/inactivaVeterinario" method="POST">
                            <input type="hidden" name="modificacion" value="<?=$Veterinarios[$i]['id_veterinario'] ?>">
                            <input type="hidden" name="decision" value="<?=$Veterinarios[$i]['visible'] ?>">
                            <button class="btn tooltipped red"  data-position="bottom" data-tooltip="Bloquear/Desbloquear Usuario" name="accion" <?= $Veterinarios[$i]['visible'] != 1? "value='Activar'": "value='Inactivar'" ?>>
                                <?php if($Veterinarios[$i]['visible'] != 1) { ?> <i class="large material-icons">lock_open</i> 
                                <?php } else { ?> <i class="large material-icons">lock</i> <?php }?>
                            </button>
                        </form>
                    </div>
                </div>
            </td>
            </tr>
            <?php
            }
            // como el parametro de si esta activo el usuario o bloqueado es un numero
            //se comprueba con codigo si es esta activo (1) o si esta bloqueado (0 o en este caso cualquier cosa)
            ?>
        </tbody>
    </table>
    <div class="col-md-12 center text-center"><!--Paginador-->
    <ul class="pagination">
        <?php if($pagina != 1){ ?>
            <li class="waves-effect blue-text"><a href="<?=BASE_URL?>admin/agregaVeterinarios?pagina=1"><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="waves-effect"><a href="<?=BASE_URL?>admin/agregaVeterinarios?pagina=<?=$pagina - 1?>"><i class="material-icons">chevron_left</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i></a></li>
    <?php
        } ?>
        
        
        <?php for($i = 1; $i <= $total_paginas; $i++){ 
            if ($i == $pagina){ ?>
                <li class="active indigo"><a href="<?=BASE_URL?>admin/agregaVeterinarios?pagina=<?=$i?>"><?=$i?></a></li>
           <?php } else{
            ?>
            <li class="waves-effect"><a href="<?=BASE_URL?>admin/agregaVeterinarios?pagina=<?=$i?>"><?=$i?></a></li>
        <?php 
            }
        } ?>

        <?php if($pagina != $total_paginas){ ?>
        <li class="waves-effect"><a href="<?=BASE_URL?>admin/agregaVeterinarios?pagina=<?=$pagina + 1?>"><i class="material-icons">chevron_right</i></a></li>
        <li class="waves-effect"><a href="<?=BASE_URL?>admin/agregaVeterinarios?pagina=<?=$total_paginas?>"><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
    <?php
        } ?>
    </ul>
</div>
</div>
</div>
</div>
</div> 