<?php 
print_r($alberguesAdmin);
?>

<table>
    <thead>
        <tr>
            <th>Identificador</th>
            <th>Nombre</th>
            <th>Direccion</th>
            <th>Fundacion</th>
            <th>Activo</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($alberguesAdmin as $albergues){ ?>
        <tr>
            <td><?= $albergues['id_albergue'] ?></td>
            <td><?= $albergues['nombre'] ?></td>
            <td><?= $albergues['direccion'] ?></td>
            <td><?= $albergues['nombreusuario']?></td>
            <td><?= $albergues['activo'] ?></td>
            <td>
                <form action="<?=BASE_URL?>admin/agregaAlbergueAdmin" method="POST">
                    <input type="hidden" name="modificacion" value="<?=$albergues['id_albergue'] ?>">
                    <button name="accion" value="Modificar">Modificar</button>
                    <button name="accion" value="Borrar">Borrar</button>
                </form>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>