<?php
    //paginador
    //Total Registro y por_pagina llegan por el controlador
    $total_paginas = ceil($totalregistro / $por_pagina);
?>  
<a href="<?= BASE_URL;?>admin/agregaAnimales"><input type="button" value="Agrega Animales"></a>
<table class="highlight centered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Año Nac.</th>
            <th>img</th>
            <th>Fecha Ing</th>
            <th>Raza</th>
            <th>Animal</th>
            <th>Albergue</th>
            <th>Fundacion</th>
            <th>Visible</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($animalesAdmin as $animal){ ?>
        <tr>
            <td><?= $animal['id_animal'] ?></td>
            <td><?= $animal['nombre'] ?></td>
            <td><?= $animal['anio_nac'] ?></td>
            <td><img src="<?=URL_BASE?>img/animales/<?=$animal['img']?>" alt="Imagen Animal" width="50"></td>
            <td><?= $animal['fecha_ingreso'] = date("d-m-Y", strtotime($animal['fecha_ingreso'])); ?></td>
            <td><?= $animal['nomraza'] ?></td>
            <td><?= $animal['nomtipo'] ?></td>
            <td><?= $animal['nomalbergue'] ?></td> 
            <td><?= $animal['nombreUser'] ?></td>
            <td><?= $activo = $animal['visible'] != 1? "No visible": "visible"?></td>
            <td>
                <form action="<?=BASE_URL?>admin/agregaAnimales" method="POST">
                    <input type="hidden" name="modificacion" value="<?=$animal['id_animal'] ?>">
                    <button name="accion" value="Modificar">Modificar</button>
                </form>
                <form action="<?=BASE_URL?>admin/inactivaPeludos" method="POST">
                    <input type="hidden" name="modificacion" value="<?=$animal['id_animal'] ?>">
                    <input type="hidden" name="decision" value="<?=$animal['visible'] ?>">
                    <button name="accion" <?= $animal['visible'] != 1? "value='Activar'": "value='Inactivar'" ?>><?= $animal['visible'] != 1? "Mostrar": "Ocultar" ?></button>
                </form>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>

<div class="col-md-12 center text-center cyan lighten-2"><!--Paginador-->
    <ul class="pagination">
        <?php if($pagina != 1){ ?>
            <li class="waves-effect blue-text"><a href="<?=BASE_URL?>admin/animales?pagina=1"><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="waves-effect"><a href="<?=BASE_URL?>admin/animales?pagina=<?=$pagina - 1?>"><i class="material-icons">chevron_left</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i></a></li>
    <?php
        } ?>
        
        
        <?php for($i = 1; $i <= $total_paginas; $i++){ 
            if ($i == $pagina){ ?>
                <li class="active"><a href="<?=BASE_URL?>admin/animales?pagina=<?=$i?>"><?=$i?></a></li>
           <?php } else{
            ?>
            <li class="waves-effect"><a href="<?=BASE_URL?>admin/animales?pagina=<?=$i?>"><?=$i?></a></li>
        <?php 
            }
        } ?>

        <?php if($pagina != $total_paginas){ ?>
        <li class="waves-effect"><a href="<?=BASE_URL?>admin/animales?pagina=<?=$pagina + 1?>"><i class="material-icons">chevron_right</i></a></li>
        <li class="waves-effect"><a href="<?=BASE_URL?>admin/animales?pagina=<?=$total_paginas?>"><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
    <?php
        } ?>
    </ul>
</div>