<?php $total_paginas = ceil($totalregistro / $por_pagina); ?>
<a href="<?= BASE_URL;?>admin/agregaAlbergueAdmin"><input type="button" value="Agrega Albergue"></a>
<table class="highlight centered">
    <thead>
        <tr>
            <th>Identificador</th>
            <th>Nombre</th>
            <th>Direccion</th>
            <th>Fundacion</th>
            <th>Activo</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($alberguesAdmin as $albergues){ ?>
        <tr>
            <td><?= $albergues['id_albergue'] ?></td>
            <td><?= $albergues['nombre'] ?></td>
            <td><?= $albergues['direccion'] ?></td>
            <td><?= $albergues['nombreusuario']?></td>
            <td><?= $visible = $albergues['activo'] != 1? "No visible": "Visible"?></td>
            <td>
                <form action="<?=BASE_URL?>admin/agregaAlbergueAdmin" method="POST">
                    <input type="hidden" name="modificacion" value="<?=$albergues['id_albergue'] ?>">
                    <button name="accion" value="Modificar">Modificar</button>
                </form>
                <form action="<?=BASE_URL?>admin/inactivaAlbergue" method="POST">
                    <input type="hidden" name="modificacion" value="<?=$albergues['id_albergue'] ?>">
                    <input type="hidden" name="decision" value="<?=$albergues['activo'] ?>">
                    <button name="accion" <?= $albergues['activo'] != 1? "value='Activar'": "value='Inactivar'" ?>><?= $albergues['activo'] != 1? "Mostrar": "Ocultar" ?></button>
                </form>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>

<div class="col-md-12 center text-center cyan lighten-2"><!--Paginador-->
    <ul class="pagination">
        <?php if($pagina != 1){ ?>
            <li class="waves-effect blue-text"><a href="<?=BASE_URL?>admin/albergues?pagina=1"><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="waves-effect"><a href="<?=BASE_URL?>admin/albergues?pagina=<?=$pagina - 1?>"><i class="material-icons">chevron_left</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i></a></li>
    <?php
        } ?>
        
        
        <?php for($i = 1; $i <= $total_paginas; $i++){ 
            if ($i == $pagina){ ?>
                <li class="active"><a href="<?=BASE_URL?>admin/albergues?pagina=<?=$i?>"><?=$i?></a></li>
           <?php } else { ?>
            <li class="waves-effect"><a href="<?=BASE_URL?>admin/albergues?pagina=<?=$i?>"><?=$i?></a></li>
        <?php 
            }
        } ?>

        <?php if($pagina != $total_paginas){ ?>
        <li class="waves-effect"><a href="<?=BASE_URL?>admin/albergues?pagina=<?=$pagina + 1?>"><i class="material-icons">chevron_right</i></a></li>
        <li class="waves-effect"><a href="<?=BASE_URL?>admin/albergues?pagina=<?=$total_paginas?>"><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
    <?php
        } ?>
    </ul>
</div>