<?php 
print_r($alberguesAdmin);
?>

<table>
    <thead>
        <tr>
            <th>Identificador</th>
            <th>Nombre</th>
            <th>Direccion</th>
            <th>Fundacion</th>
            <th>Activo</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($alberguesAdmin as $albergues){ ?>
        <tr>
            <td><?= $albergues['id_albergue'] ?></td>
            <td><?= $albergues['nombre'] ?></td>
            <td><?= $albergues['direccion'] ?></td>
            <td><?= $albergues['nombreusuario']?></td>
            <td><?= $albergues['activo'] ?></td>
        </tr>
        <?php } ?>
    </tbody>
</table>