<?php 
    $total_paginas = ceil($totalregistro / $por_pagina); 
    $seleccionado = isset($Busqueda)? $Busqueda : "0";
?>
<form action="<?=BASE_URL?>admin/adopciones" method="POST">
    <label for="">Filtra por albergue especifico</label>
    <select name="AlbergueEsp" id="">
        <option value="0">Seleccionar</option>
        <?php foreach ($albergues as $key){ ?>
        <option <?php if($seleccionado == $key['id_albergue']){echo "selected";} ?> value="<?=$key['id_albergue'];?>"><?=$key['nombre']?></option>
        <?php }?>
    </select>
    <button>Buscar</button>
</form>
<?php if($adopciones != false){ ?>
<table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Fecha de Peticion</th>
        <th>Animal</th>
        <th>Usuario</th>
        <th>Albergue</th>
        <th>Estado</th>
      </tr>  
    </thead>
    <tbody>
    <?php foreach($adopciones as $adopcion){ ?>
            <tr>
                <td><?= $adopcion['id_adopcion']; ?></td>
                <td><?= $fecha = date("d-m-Y",strtotime($adopcion['fecha_adopcion'])); ?></td><!--ORDENA LA FECHA -->
                <td><?= $adopcion['nombreanimal']; ?></td>
                <td><?= $adopcion['nombreusuario']; ?></td>
                <td><?= $adopcion['nombrealbergue']; ?></td>
                <td><?= $adopcion['nombre_estado']; ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
<div class="col-md-12 center text-center cyan lighten-2"><!--Paginador-->
    <ul class="pagination">
        <?php if($pagina != 1){ ?>
            <li class="waves-effect blue-text"><a href="<?=BASE_URL?>admin/razasAnimal?pagina=1"><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="waves-effect"><a href="<?=BASE_URL?>admin/razasAnimal?pagina=<?=$pagina - 1?>"><i class="material-icons">chevron_left</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i></a></li>
    <?php
        } ?>
        
        
        <?php for($i = 1; $i <= $total_paginas; $i++){ 
            if ($i == $pagina){ ?>
                <li class="active"><a href="<?=BASE_URL?>admin/razasAnimal?pagina=<?=$i?>"><?=$i?></a></li>
           <?php } else { ?>
            <li class="waves-effect"><a href="<?=BASE_URL?>admin/razasAnimal?pagina=<?=$i?>"><?=$i?></a></li>
        <?php 
            }
        } ?>

        <?php if($pagina != $total_paginas){ ?>
        <li class="waves-effect"><a href="<?=BASE_URL?>admin/razasAnimal?pagina=<?=$pagina + 1?>"><i class="material-icons">chevron_right</i></a></li>
        <li class="waves-effect"><a href="<?=BASE_URL?>admin/razasAnimal?pagina=<?=$total_paginas?>"><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
    <?php
        } ?>
    </ul>
</div>

<?php } else { ?>

    <h1>Aun no Existen adopciones</h1>

<?php } ?>