<?php
$total_paginas = ceil($totalregistro / $por_pagina);
if($adopciones == false) { ?>
<!--Esto se agrego porque si no tiene adopciones el albergue ps saca error -->

        <h1>Aun no tiene adopciones</h1>

<?php } else { ?>
<table>
        <thead>
                <tr>
                    <th>ID</th>
                    <th>Fecha de peticion</th>
                    <th>Animal</th>
                    <th>Usuario</th>
                    <th>Contacto</th>
                    <th>Albergue</th>
                    <th>Estado</th>
                    <th>Acciones</th><!--Quitar y colocar botones-->
                </tr>
        </thead>
       <tbody>
        <?php foreach($adopciones as $adopcion){ ?>
            <tr>
                <td><?= $adopcion['id_adopcion']; ?></td>
                <td><?= $fecha = date("d-m-Y",strtotime($adopcion['fecha_adopcion'])); ?></td><!--ORDENA LA FECHA -->
                <td><?= $adopcion['nombreanimal']; ?></td>
                <td><?= $adopcion['nombreusuario']; ?></td>
                <td><?= $adopcion['telefono']; ?></td>
                <td><?= $adopcion['nombrealbergue']; ?></td>
                <td><?= $adopcion['nombre_estado']; ?></td>
                <td>
                        <form action="<?=BASE_URL?>fundacion/destinoAdopcion" method="GET">
                                <input type="hidden" name="modificacion" value="<?=$adopcion['id_adopcion'] ?>">
                                <input type="hidden" name="usuario" value="<?=$_SESSION['iduser'];?>">
                                <button name="accion" value="Completada">Completada</button>
                        </form>
                                <button href='#idmodal' class='modal-trigger'>Cancelada</button>
                </td>
            </tr>
        <?php } ?>
       </tbody>
</table>
<div class="col-md-12 center text-center cyan lighten-2"><!--Paginador-->
    <ul class="pagination">
        <?php if($pagina != 1){ ?>
            <li class="waves-effect blue-text"><a href="<?=BASE_URL?>fundacion/verAdopciones?pagina=1"><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="waves-effect"><a href="<?=BASE_URL?>fundacion/verAdopciones?pagina=<?=$pagina - 1?>"><i class="material-icons">chevron_left</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i></a></li>
    <?php
        } ?>
        
        
        <?php for($i = 1; $i <= $total_paginas; $i++){ 
            if ($i == $pagina){ ?>
                <li class="active"><a href="<?=BASE_URL?>fundacion/verAdopciones?pagina=<?=$i?>"><?=$i?></a></li>
           <?php } else{
            ?>
            <li class="waves-effect"><a href="<?=BASE_URL?>fundacion/verAdopciones?pagina=<?=$i?>"><?=$i?></a></li>
        <?php 
            }
        } ?>

        <?php if($pagina != $total_paginas){ ?>
        <li class="waves-effect"><a href="<?=BASE_URL?>fundacion/verAdopciones?pagina=<?=$pagina + 1?>"><i class="material-icons">chevron_right</i></a></li>
        <li class="waves-effect"><a href="<?=BASE_URL?>fundacion/verAdopciones?pagina=<?=$total_paginas?>"><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
    <?php
        } ?>
    </ul>
</div>
<?php } ?>

<div id="idmodal" class="modal">
    <div class="modal-content">
        <p class="black-text">¿Por que fue rechazada la Peticion?</p>
        <form action="<?=BASE_URL?>fundacion/destinoAdopcion" method="GET">
                <input type="text" name="razoncancelado">
                <input type="hidden" name="modificacion" value="<?=$adopcion['id_adopcion'] ?>">
                <input type="hidden" name="usuario" value="<?=$_SESSION['iduser'];?>">
                <button class="btn" name="accion" value="Cancelada">Enviar</button>
            </form>
        <div class="modal-footer">
            <a href="#" class="btn modal-close">Cancelar</a>
        </div>
    </div>
</div>