<?php if($adopciones == false) { ?>
<!--Esto se agrego porque si no tiene adopciones el albergue ps saca error -->

        <h1>Aun no tiene adopciones</h1>

<?php } else { ?>
<table>
        <thead>
                <tr>
                    <th>ID</th>
                    <th>Fecha de peticion</th>
                    <th>Animal</th>
                    <th>Usuario</th>
                    <th>Albergue</th>
                    <th>Estado</th>
                    <th>Acciones</th><!--Quitar y colocar botones-->
                </tr>
        </thead>
       <tbody>
        <?php foreach($adopciones as $adopcion){ ?>
            <tr>
                <td><?= $adopcion['id_adopcion']; ?></td>
                <td><?= $fecha = date("d-m-Y",strtotime($adopcion['fecha_adopcion'])); ?></td><!--ORDENA LA FECHA -->
                <td><?= $adopcion['nombreanimal']; ?></td>
                <td><?= $adopcion['nombreusuario']; ?></td>
                <td><?= $adopcion['nombrealbergue']; ?></td>
                <td><?= $adopcion['nombre_estado']; ?></td>
                <td>
                        <form action="<?=BASE_URL?>fundacion/destinoAdopcion" method="GET">
                                <input type="hidden" name="modificacion" value="<?=$adopcion['id_adopcion'] ?>">
                                <input type="hidden" name="usuario" value="<?=$_SESSION['iduser'];?>">
                                <button name="accion" value="Completada">Completada</button>
                                <button name="accion" value="Cancelada">Cancelada</button>
                        </form>
                </td>
            </tr>
        <?php } ?>
       </tbody>
</table>
<?php } ?>