<?php
//teoricamente los siguientes datos siempre llegaran no importa que

$identificador_Adopcion = isset($adopcion)? $adopcion[0]['id_adopcion']:"";
$fecha = isset($adopcion)? $adopcion[0]['fecha_adopcion']:"";
$usuario = isset($adopcion)? $adopcion[0]['nombreUsuario']:"";
$animal = isset($adopcion)? $adopcion[0]['nombreAnimal']:"";
$estado = isset($adopcion)? $adopcion[0]['estado']:"";
?>
<h1>
    Vista de modificar Adopcion Porque anteriormente no teniamos un <br>
    Formulario para hacerlo ya que es automatico.
</h1>
<?php print_r($adopcion) ?>
<br>
<?php print_r($estado_adop) ?>
<!--Esto hay que quitarlo y solo dejar dos botones completada y cancelada-->
<div class="card text-center">
      <div class="card-body">
        <h4 class="card-title">Title</h4>
        <p class="card-text">
          Pagina para Modificar Pedidos de Adopcion.
        </p>
        <form action="<?=BASE_URL;?>fundacion/modificacionAdopcion" method="post">
        <label for="">ID Adopcion: <?= $identificador_Adopcion?></label>
        <input type="hidden" name="Identificador_adop" value="<?=$identificador_Adopcion?>"><br>
        <label for="">Fecha</label>
        <input type="text" name="fecha" value="<?= $fecha?>">
        <label for="">Usuario Solicitante</label>
        <input type="text" name="Usuario" value="<?=$usuario?>">
        <label for="">Animal Solicitando</label>
        <input type="text" name="Animal" value="<?=$animal?>"><br>
        <select name="Estado_adopcion" id="">
            <option value="0">Seleccionar</option>
        <?php foreach ($estado_adop as $key) {?>
          <option <?php if($estado == $key['id_tipo_estado']){ echo"selected"; } ?> value="<?= $key['id_tipo_estado']; ?>"><?= $key['nombre_estado']; ?></option>
          <?php
          }
        ?>
        </select>
        <button name="accion" value="Modificar">Aceptar</button>
        </form>
      </div>
    </div>