Ver albergues de la fundacion <br>
Mostrara los albergues que le pertenecen a la fundacion seleccionada

<?php 
print_r($userfund);
?>

<table>
    <thead>
        <tr>
            <th>Identificador</th>
            <th>Nombre</th>
            <th>Direccion</th>
            <th>Activo</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($userfund as $albergues){ ?>
        <tr>
            <td><?= $albergues['id_albergue'] ?></td>
            <td><?= $albergues['nombre'] ?></td>
            <td><?= $albergues['direccion'] ?></td>
            <td><?= $albergues['activo'] ?></td>
        </tr>
        <?php } ?>
    </tbody>
</table>