<?php
$total_paginas = ceil($totalregistro / $por_pagina);

if(isset($_GET['error'])){
	
	echo "<h1>" . $_GET['error'] . "</h1>";
	
}


if($albergues == false){ ?>
    <h1>Aun no tiene albergues en los que registrar Animales</h1>
<?php
} else { ?>
    <a href="<?= BASE_URL;?>fundacion/agregaAnimal"><input type="button" value="Agregar Animal"></a>
<?php } ?>
<?php if($useranimales == false){ ?>

    <h1>Aun no tiene Animales</h1>

<?php
} else{ ?>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Año Nac.</th>
            <th>img</th>
            <th>Fecha Ing</th>
            <th>Raza</th>
            <th>Animal</th>
            <th>Albergue</th>
            <th>Movimiento</th>
            <th>Visible</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($useranimales as $animal){ ?>
        <tr>
            <td><?= $animal['id_animal'] ?></td>
            <td><?= $animal['nombre'] ?></td>
            <td><?= $animal['anio_nac'] ?></td>
            <td><img src="<?=URL_BASE?>img/animales/<?=$animal['img']?>" alt="Imagen Animal" width="50"></td>
            <td><?= $animal['fecha_ingreso'] ?></td>
            <td><?= $animal['nomraza'] ?></td>
            <td><?= $animal['nomtipo'] ?></td>
            <td><?= $animal['nomalbergue'] ?></td>
            <td><?= $activo = $animal['visible'] != 1? "No visible": "visible"?></td>
            <td>
                <form action="<?=BASE_URL?>fundacion/agregaAnimal" method="POST">
                    <input type="hidden" name="modificacion" value="<?=$animal['id_animal'] ?>">
                    <button name="accion" value="Modificar">Modificar</button>
                </form>
                <form action="<?=BASE_URL?>fundacion/inactivaPeludos" method="POST">
                    <input type="hidden" name="modificacion" value="<?=$animal['id_animal'] ?>">
                    <input type="hidden" name="decision" value="<?=$animal['visible'] ?>">
                    <button name="accion" <?= $animal['visible'] != 1? "value='Activar'": "value='Inactivar'" ?>><?= $animal['visible'] != 1? "Mostrar": "Ocultar" ?></button>
                </form>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>

<div class="col-md-12 center text-center cyan lighten-2"><!--Paginador-->
    <ul class="pagination">
        <?php if($pagina != 1){ ?>
            <li class="waves-effect blue-text"><a href="<?=BASE_URL?>fundacion/animales?pagina=1"><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="waves-effect"><a href="<?=BASE_URL?>fundacion/animales?pagina=<?=$pagina - 1?>"><i class="material-icons">chevron_left</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i></a></li>
    <?php
        } ?>
        
        
        <?php for($i = 1; $i <= $total_paginas; $i++){ 
            if ($i == $pagina){ ?>
                <li class="active"><a href="<?=BASE_URL?>fundacion/animales?pagina=<?=$i?>"><?=$i?></a></li>
           <?php } else{
            ?>
            <li class="waves-effect"><a href="<?=BASE_URL?>fundacion/animales?pagina=<?=$i?>"><?=$i?></a></li>
        <?php 
            }
        } ?>

        <?php if($pagina != $total_paginas){ ?>
        <li class="waves-effect"><a href="<?=BASE_URL?>fundacion/animales?pagina=<?=$pagina + 1?>"><i class="material-icons">chevron_right</i></a></li>
        <li class="waves-effect"><a href="<?=BASE_URL?>fundacion/animales?pagina=<?=$total_paginas?>"><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
    <?php
        } ?>
    </ul>
</div>

<?php } ?>