<a href="<?= BASE_URL;?>fundacion/agregaAlberg"><input type="button" value="Agregar Albergue"></a>

<?php if($userfund == false){ ?>
    <h1>Aun no tiene Albergues</h1>
<?php
} else { ?>
<table>
    <thead>
        <tr>
            <th>Identificador</th>
            <th>Nombre</th>
            <th>Direccion</th>
            <th>Activo</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($userfund as $albergues){ ?>
        <tr>
            <td><?= $albergues['id_albergue'] ?></td>
            <td><?= $albergues['nombre'] ?></td>
            <td><?= $albergues['direccion'] ?></td>
            <td><?= $albergues['activo'] ?></td>
            <td>
                <form action="<?=BASE_URL?>fundacion/agregaAlberg" method="POST">
                    <input type="hidden" name="modificacion" value="<?=$albergues['id_albergue'] ?>">
                    <button name="accion" value="Modificar">Modificar</button>
                </form>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>

<?php } ?>