<h1>Pag donde saldran los animales</h1>
<?php
echo "Array q se trae cuando vienes para aca";
print_r($animales);

?>

<table>
        <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Año Nacimiento</th>
                    <th>img</th>
                    <th>Descripcion</th>
                    <th>Fecha ingreso</th>
                    <th>Nom Raza</th>
                    <th>Tamaño</th>
                    <th>Albergue</th>
                </tr>
        </thead>
       <tbody>
        <?php foreach($animales as $animal){ ?>
            <tr>
                    <td><?= $animal['id_animal']; ?></td>
                    <td><!--
                        hay dos formas 
                        1.enviar literalmente por url todos los datos del animal 
                        2. o enviar el id solo y hacer una consulta para ver
                        (para mi la mejor seria la 2da para no saturar la url)
                        pq literal mira le envio el id y el nombre y mira la pedazo de url q se enviar
                        <?= BASE_URL?>session/mascota?idanimal=<?=$animal['id_animal']?>&nombre=<?=$animal['nombre']?>
                        -->
                        <a href="<?= BASE_URL?>session/mascota?idanimal=<?=$animal['id_animal']?>"><?= $animal['nombre']; ?></a>
                    </td>
                    <td><?= $animal['anio_nac']; ?></td>

                    <td>
                        <img src="<?=URL_BASE;?>img/animales/<?= $animal['img']?>"  width="50" alt="Foto Animal">
                    </td>

                    <td><?= $animal['descripcion']; ?></td>
                    <td><?= $animal['fecha_ingreso']; ?></td>
                    <td><?= $animal['nomRaza']; ?></td>
                    <td><?= $animal['tamanio']; ?></td>
                    <td><?= $animal['albergue']; ?></td>
                    
                    </td>
            </tr>
        <?php } ?>
       </tbody>
</table>
