<?php
if (isset($_SESSION)){
  $role = (isset($_SESSION['rol']))?$_SESSION['rol']:"";
  $id_user = (isset($_SESSION['iduser']))?$_SESSION['iduser'] :"";
  //sin esto lo demas explota xD
}
?>
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      <?= $titulo; ?>
    </title>
<head>
  <!--Importar Iconos-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Importar Materialize-->
  <link type="text/css" rel="stylesheet" href="<?= URL_ASSETS; ?>/materialize/css/style.css"  media="screen,projection"/>  
  <link type="text/css" rel="stylesheet" href="<?= URL_ASSETS; ?>/materialize/css/materialize.css"  media="screen,projection"/>
</head>
<body style="background: url(<?= URL_ASSETS; ?>/wallpaper.jpg) no-repeat fixed">
<br>
<nav class="indigo z-depth-4 nav-extended container" style="border-radius: 25px; padding-left: 20px; padding-right: 10px;">

    <div class="nav-wrapper">
      <!--El nav se solapa con el titulo pq creo que estan en el mismo div-->
      <!--Creo q si estas en admin no deberia llevarte a la pag pero bueh-->
        <a href="<?= BASE_URL; ?>" class="brand-logo s1"><img style="padding-top: 15px; padding-bottom: 10px;  height: 60px;" class="responsive-img small" src="<?= URL_ASSETS; ?>/logo.png"></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><a href='<?= BASE_URL; ?>session/catalogoAnimales'>Catalogo</a></li>
      <li><a href='<?= BASE_URL; ?>session/catalogoVeterinarios'> Veterinarios</a></li>
      <!-- Botones NavBar-->
        <?php if (isset($_SESSION)){ ?>
          
          <?php if($role == "1"){ ?> 
            <!--Aca irian todas las funciones de Admin-->
            <!--Los Botones ps como los dividi antes o como sea mejor-->
            <li><a class='dropdown-trigger' href='#' data-target='dropdown1'>Admin</a></li>
          <?php } ?>
          <!--Aca irian los botones que le pertecen a Fundacion-->
          <?php if($role == "3"){ ?> 
            <li><a class='dropdown-trigger' href='#' data-target='dropdown2'>Fundacion</a></li> 
          <?php } ?>
          <!--Aca irian los botones que le pertenecen al rol de tienda-->
          <?php if($role == "4"){ ?>
            <li><a class='dropdown-trigger' href='#' data-target='dropdown3'>Tienda</a></li>
          <?php } ?>
        <?php } ?>
        <!-- Estado de Sesion -->
        <!---
          Hay que crear un cierre de sesion para los otros usuarios
          Pq ese cierre te lleva al login de admin :V
        -->
        <?php
          if(isset($_SESSION['usuario'])){
            $username = $_SESSION['usuario'];
              echo "<li>".$username."</li>";
              if($role == "1"){
                echo "<li><a href='". BASE_URL ."admin/index'>Cerrar Sesion</a></li>";
              } else {
                echo "<li><a href='". BASE_URL ."home/destroy_session'>Cerrar Sesion</a></li>";
              }
        }
        ?>

        <?php if(!isset($_SESSION['usuario'])){ ?>
        <li>
          <a class="nav-link" href="<?= BASE_URL;?>session/login" role="button" aria-expanded="false">
            <i class="material-icons">account_circle</i>
          </a>
        </li>

        <li>
          <a class="nav-link" href="<?= BASE_URL;?>session/register" role="button" aria-expanded="false">
            <i class="material-icons">cancel</i>
          </a>
        </li>
        
        <?php }?>

        <!-- Contenido de Dropdowns -->
        <!--Admin-->
        <ul id='dropdown1' class='dropdown-content'>
          <li><a href="<?= BASE_URL;?>admin/tipoAnimal">Agregar Tipo Animal</a></li>
          <li><a href="<?= BASE_URL;?>admin/razasAnimal">Agrega Razas</a></li>
          <li><a href="<?= BASE_URL;?>admin/agregaUsuarios">Agrega Usuarios</a></li>
          <li><a href="<?= BASE_URL;?>admin/agregaAnimales">Agrega Animales</a></li>
          <li><a href="<?= BASE_URL;?>admin/agregaVeterinarios">Agrega Veterinarios</a></li>
          <li><a href="<?= BASE_URL;?>admin/agregaAlbergueAdmin">Agrega Albergues</a></li>
          <li><a href="<?= BASE_URL;?>admin/animales">Ver Animales</a></li>
          <li><a href="<?= BASE_URL;?>admin/albergues">Ver Albergues</a></li>
          <li><a href="#">Ver Adopciones (En proceso)</a></li>
          <!--Ver adopciones falta-->
        </ul>
          <!--Fundacion-->
        <ul id='dropdown2' class='dropdown-content'>
          <li><a href="<?= BASE_URL;?>fundacion/agregaAlberg">Agrega Albergue</a></li>
          <li><a href="<?= BASE_URL;?>fundacion/agregaAnimal">Agregar Animal</a></li>
          <li><a href="<?= BASE_URL;?>fundacion/verAdopciones">Ver peticiones de Adopcion</a></li>
          <li><a href="<?= BASE_URL;?>fundacion/albergues">Ver Albergues</a></li>
          <li><a href="<?= BASE_URL;?>fundacion/animales">Ver Animales</a></li>
        </ul>
          <!--Vendedores-->
        <ul id='dropdown3' class='dropdown-content'>
          <li><a href="#!">EN CONSTRUCCIÓN</a></li>
        </ul>
      </ul>
    </div>
  </nav>


  <!-- Contenido Pirncipal -->
    <main>
        <div class="white-text">
            <?php require_once 'views/' . $vista; ?>
        </div>
    </main>
   <!-- Footer --> 
    <footer class="page-footer indigo">
            <div class="container center-align">
            © 2022 IsanJeru & Duglah
            </div>
            <br>
        </footer>


  <!--Funciones JavaScript-->
  <script type="text/javascript" src="<?= URL_ASSETS; ?>/materialize/js/materialize.min.js"></script>
  <script> 
  M.AutoInit();
    document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.carousel');
    var instances = M.Carousel.init(elems, options);
  });
  </script>
</body>


