<?php
if (isset($_SESSION)){
  $role = (isset($_SESSION['rol']))?$_SESSION['rol']:"";
  //sin esto lo demas explota xD
}
?>
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      <?= $titulo; ?>
    </title>
<head>
  <!--Importar Iconos-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Importar Materialize-->
  <link type="text/css" rel="stylesheet" href="<?= URL_ASSETS; ?>/materialize/css/materialize.min.css"  media="screen,projection"/>
  <link type="text/css" rel="stylesheet" href="<?= URL_ASSETS; ?>/materialize/css/style.css"  media="screen,projection"/>  
</head>
<body>
<nav>
    <div class="container nav-wrapper">
      <a href="<?= BASE_URL; ?>" class="brand-logo">Polipropeludos</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><a class='btn' href='<?= BASE_URL; ?>'>Inicio</a></li>
      <li><a class='btn' href='<?= BASE_URL; ?>session/catalogoAnimales'>Catalogo (Ver animales)</a></li>
        <!-- Botones NavBar-->
        <?php if (isset($_SESSION)){ ?>
          <?php if($role == "1"){ echo "<li><a class='dropdown-trigger btn' href='#' data-target='dropdown1'>Admin</a></li>"; } ?>
          <?php if($role == "3"){ ?> <li><a class='dropdown-trigger btn' href='#' data-target='dropdown2'>Fundacion</a></li> <?php } ?>
          <li><a class='dropdown-trigger btn' href='#' data-target='dropdown3'>Tienda</a></li>
          <li><a class='dropdown-trigger btn' href='#' data-target='dropdown4'>Usuario</a></li>
        <?php } ?>
        <!-- Estado de Sesion -->
        <?php
          if(isset($_SESSION['usuario'])){
            $username = $_SESSION['usuario'];
              echo "<li>".$username."</li>";
              echo "<li><a href='". BASE_URL ."admin/index'>Cerrar Sesion</a></li>";
        }
        ?>

        <li>
          <a class="nav-link" href="<?= BASE_URL;?>session/login" role="button" aria-expanded="false">
            <i class="material-icons">account_circle</i>
          </a>
        </li>

        <li>
          <a class="nav-link" href="<?= BASE_URL;?>session/register" role="button" aria-expanded="false">
            <i class="material-icons">edit</i>
          </a>
        </li>

        <!-- Contenido de Dropdowns -->
        <ul id='dropdown1' class='dropdown-content'>
          <li><a href="<?= BASE_URL;?>admin/tipoAnimal">Agregar Tipo Animal</a></li>
          <li><a href="<?= BASE_URL;?>admin/razasAnimal">Agrega Razas</a></li>
          <li><a href="<?= BASE_URL;?>admin/agregaUsuarios">Agrega Usuarios</a></li>
          <li><a href="<?= BASE_URL;?>admin/agregaAnimales">Agrega Animales</a></li>
        </ul>

        <ul id='dropdown2' class='dropdown-content'>
          <li><a href="<?= BASE_URL;?>fundacion/agregaAlberg">Agrega Albergue</a></li>
          <li><a href="<?= BASE_URL;?>fundacion/agregaAnimal">Agregar Animal</a></li>
        </ul>

        <ul id='dropdown3' class='dropdown-content'>
          <li><a href="#!">No hay nada xd</a></li>
        </ul>

        <ul id='dropdown4' class='dropdown-content'>
          <li><a href="#!">one</a></li>
          <li><a href="#!">two</a></li>
          <li class="divider" tabindex="-1"></li>
          <li><a href="#!">three</a></li>
          <li><a href="#!"><i class="material-icons">view_module</i>four</a></li>
          <li><a href="#!"><i class="material-icons">cloud</i>five</a></li>
        </ul>
      </ul>
    </div>
  </nav>
  <!-- Contenido Pirncipal -->
    <main>
        <div class="container">
            <?php require_once 'views/' . $vista; ?>
        </div>
    </main>
   <!-- Footer --> 
    <footer class="page-footer ">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>


  <!--Funciones JavaScript-->
  <script type="text/javascript" src="<?= URL_ASSETS; ?>/materialize/js/materialize.min.js"></script>
  <script> M.AutoInit() </script>
</body>

