<?php 
    //paginador
    //Total Registro y por_pagina llegan por el controlador
    $total_paginas = ceil($totalregistro / $por_pagina);
    if($fundaciones != false){
?>
<div class="row" style="padding-top: 5%; padding-bottom: 10px;">
<div class="login-card col s10 offset-s1">
    <div class="row" style="padding-left: 10px; padding-right: 10px;">
    <?php foreach($fundaciones as $fundacion){ ?>
    <div class="card small indigo col s3">
        <div class="card-title  center-align" style="padding-top: 10px; padding-bottom: 10px;">
        <span>Fundación: <br> <?= $fundacion['nombre']; ?></span>
        </div>
        <div class="card-action">

            <div class="align">
            <i class="material-icons">person</i>
            <span> RIF de Fundación:</span>
            </div>
            <span><?= $fundacion['cedula']; ?></span>
        
            <div class="align">
            <i class="material-icons">phone</i>
            <span> Telefono de Contacto:</span>
            </div>
            <span><?= $fundacion['telefono']; ?></span>

            <div class="align">
            <i class="material-icons">home</i>
            <span> Direccion:</span>
            </div>
            <?= $fundacion['direccion']; ?>

            <div class="center-align" style="padding-top: 10px;">
        </div>
        </div>
    </div>
    <?php } ?>
    </div>
</div>
</div>
<div class="div" style="padding-left: 20%; padding-right: 20%;">
<div class="col-md-12 center text-center card"><!--Paginador-->
    <ul class="pagination">
        <?php if($pagina != 1){ ?>
            <!-- PA q sirve esto? <?= $fun ?> -->
            <li class="waves-effect blue-text"><a href="<?=BASE_URL?>session/catalogoFundaciones?pagina=1<?=$filtro != ""? "&filtro=".$filtro: "";?>"><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="waves-effect"><a href="<?=BASE_URL?>session/catalogoFundaciones?pagina=<?=$pagina - 1?><?=$filtro != ""? "&filtro=".$filtro: "";?>"><i class="material-icons">chevron_left</i></a></li>
        <?php
        } else { ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i></a></li>
    <?php
        } ?>
        
        
        <?php for($i = 1; $i <= $total_paginas; $i++){ 
            if ($i == $pagina){ ?>
                <li class="active indigo"><a href="<?=BASE_URL?>session/catalogoFundaciones?pagina=<?=$i?><?=$filtro != ""? "&filtro=".$filtro: "";?>"><?=$i?></a></li>
           <?php } else {
            ?>
            <li class="waves-effect"><a href="<?=BASE_URL?>session/catalogoFundaciones?pagina=<?=$i?><?=$filtro != ""? "&filtro=".$filtro: "";?>"><?=$i?></a></li>
        <?php 
            }
        } ?>

        <?php if($pagina != $total_paginas){ ?>
        <li class="waves-effect"><a href="<?=BASE_URL?>session/catalogoFundaciones?pagina=<?=$pagina + 1?><?=$filtro != ""? "&filtro=".$filtro: "";?>"><i class="material-icons">chevron_right</i></a></li>
        <li class="waves-effect"><a href="<?=BASE_URL?>session/catalogoFundaciones?pagina=<?=$total_paginas?><?=$filtro != ""? "&filtro=".$filtro: "";?>"><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
        <?php
        } else { ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
    <?php
        } ?>
    </ul>
</div>
<?php } else { ?>

    <h1>Aun no se encuentran Peluditos para adoptar Disponibles</h1>

<?php } ?>

<!-- -------------------------------------------------------------------------------------------------------------------- -->