<?php 
if(isset($_GET['error'])){
        echo "<h1>". $_GET['error'] ."</h1>";
}

?>
        
        <h1>Esta seria la vista inicial de la pag. cuando no introduzcas nada por URL</h1>
        <h2>Bienvenidos a la vista principal</h2>
        <h2>Agregar (Agregar)</h2>
        <ul>
                <li><p>Mascotas /YA</p></li>
                <li><p>Mascota Detallado (Hacerle diseño)</p></li>
                <li><p>Solicitud Animal (Hacerle Diseño)</p></li>
                <li><p>Ver Veterinarios (Hacerle Diseño)</p></li>
                <li><p>Login Con Session (Ya o eso creo)</p></li>
                <li><p>Terminar Register (Ya o eso creo)</p></li>
                <li><p>Ver las peticiones de adopcion como fundacion (hacerle diseño)</p></li>
                <li><p>
                        Acomodar el registrar albergue en fundacion pq ellos
                        no deberia poder escojer a que usuario asignarselo.(YA)
                </p></li>
                <li><p>
                        Borrar fundacion.phtml pq esa era la vista donde llegabas cuando logueabas pero ya na
                        y el de vendedor o eso creo
                </p></li>
                <li><p>Ver productos Tienda</p></li>
                <li><p>
                        que las vistas reciban errores
                        y si reciben pues se muestren si llegan
                </p></li>
        </ul>