        <h1>Esta seria la vista inicial de la pag. cuando no introduzcas nada por URL</h1>
        <h2>Bienvenidos a la vista principal</h2>
        <h2>Agregar (Agregar)</h2>
        <ul>
                <li><p>Mascotas /YA</p></li>
                <li><p>Mascota Detallado (Hacerle diseño)</p></li>
                <li><p>Solicitud Animal (Hacerle Diseño)</p></li>
                <li><p>Ver Veterinarios</p></li>
                <li><p>Login Con Session</p></li>
                <li><p>Terminar Register</p></li>
                <li><p>Ver productos Tienda</p></li>
                <li><p>que las vistas reciban errores
                        y si reciben pues se muestren si llegan
                </p></li>
         </ul>