<h1>Vista de los veterinarios que se recomiendan por Polipropeludos</h1>

<?php
    //paginador
    //Total Registro y por_pagina llegan por el controlador
    $total_paginas = ceil($totalregistro / $por_pagina);
?>  
<table>
        <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Telefono</th>
                    <th>Direccion</th>
                    <th>Imagen</th>
                    <th>Visible</th>
                </tr>
        </thead>
       <tbody>
        <?php foreach($veterinarios as $veterinario){ ?>
            <tr>
                    <td><?= $veterinario['id_veterinario']; ?></td>
                    <td><!--
                        hay dos formas 
                        1.enviar literalmente por url todos los datos del animal 
                        2. o enviar el id solo y hacer una consulta para ver
                        (para mi la mejor seria la 2da para no saturar la url)
                        pq literal mira le envio el id y el nombre y mira la pedazo de url q se enviar
                        <?= BASE_URL?>session/mascota?idanimal=<?=$veterinario['id_animal']?>&nombre=<?=$animal['nombre']?>
                        -->
                        <a href="<?= BASE_URL?>session/veterinario?idveterinario=<?=$veterinario['id_veterinario']?>"><?= $veterinario['nombre']; ?></a>
                    </td>
                    <td><?= $veterinario['tlf']; ?></td>
                    <td><?= $veterinario['direccion']; ?></td>
                    <td>
                        <img src="<?=URL_BASE;?>img/veterinarios/<?= $veterinario['img']?>"  width="50" alt="foto veterinario">
                    </td>
                    <td><?= $veterinario['visible']; ?></td><!--quitar esto obviamente-->
            </tr>
        <?php } ?>
       </tbody>
</table>
<div class="col-md-12 center text-center cyan lighten-2"><!--Paginador-->
    <ul class="pagination">
        <?php if($pagina != 1){ ?>
            <li class="waves-effect blue-text"><a href="<?=BASE_URL?>session/catalogoVeterinarios?pagina=1"><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="waves-effect"><a href="<?=BASE_URL?>session/catalogoVeterinarios?pagina=<?=$pagina - 1?>"><i class="material-icons">chevron_left</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i></a></li>
    <?php
        } ?>
        
        
        <?php for($i = 1; $i <= $total_paginas; $i++){ 
            if ($i == $pagina){ ?>
                <li class="active"><a href="<?=BASE_URL?>session/catalogoVeterinarios?pagina=<?=$i?>"><?=$i?></a></li>
           <?php } else{
            ?>
            <li class="waves-effect"><a href="<?=BASE_URL?>session/catalogoVeterinarios?pagina=<?=$i?>"><?=$i?></a></li>
        <?php 
            }
        } ?>

        <?php if($pagina != $total_paginas){ ?>
        <li class="waves-effect"><a href="<?=BASE_URL?>session/catalogoVeterinarios?pagina=<?=$pagina + 1?>"><i class="material-icons">chevron_right</i></a></li>
        <li class="waves-effect"><a href="<?=BASE_URL?>session/catalogoVeterinarios?pagina=<?=$total_paginas?>"><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
    <?php
        } ?>
    </ul>
</div>