<?php
    //paginador //Total Registro y por_pagina llegan por el controlador
    $total_paginas = ceil($totalregistro / $por_pagina);
    if($veterinarios != false){
?>
<div class="row" style="padding-top: 5%; padding-bottom: 10px;">
<div class="login-card col s10 offset-s1">
    <div class="row" style="padding-left: 10px; padding-right: 10px;">
    <?php foreach($veterinarios as $veterinario){ ?>
    <div class="card indigo col s4">
        <div class="card-title align center-align" style="padding-top: 10px; padding-bottom: 10px;">
        <i class="material-icons">label</i>
        <span> Nombre: <?= $veterinario['nombre']; ?></span>
        </div>
        <div class="card-image">
        <img class="responsive-img" src="<?=URL_BASE;?>img/veterinarios/<?= $veterinario['img']?>" alt="Foto Animal">
        </div>
        <div class="card-action">
            <div class="align">
            <i class="material-icons">phone</i>
            <span> Telefono de Contacto:</span>
            </div>
            <span><?= $veterinario['tlf']; ?></span>
            <div class="align">
            <i class="material-icons">home</i>
            <span> Direccion de Consultorio:</span>
            </div>
            <?= $veterinario['direccion']; ?>
            <div class="center-align" style="padding-top: 10px;">
            <a class="btn orange darken-3" href="<?= BASE_URL?>session/veterinario?idveterinario=<?=$veterinario['id_veterinario']?>">Detalles</a>
        </div>
        </div>
    </div>
    <?php } ?>
    </div>
</div>
</div>

<div class="col-md-12 center text-center"><!--Paginador-->
    <ul class="pagination">
        <?php if($pagina != 1){ ?>
            <li class="waves-effect blue-text"><a href="<?=BASE_URL?>session/catalogoVeterinarios?pagina=1"><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="waves-effect"><a href="<?=BASE_URL?>session/catalogoVeterinarios?pagina=<?=$pagina - 1?>"><i class="material-icons">chevron_left</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i><i class="material-icons">chevron_left</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_left</i></a></li>
    <?php
        } ?>
        
        
        <?php for($i = 1; $i <= $total_paginas; $i++){ 
            if ($i == $pagina){ ?>
                <li class="active"><a href="<?=BASE_URL?>session/catalogoVeterinarios?pagina=<?=$i?>"><?=$i?></a></li>
           <?php } else{
            ?>
            <li class="waves-effect"><a href="<?=BASE_URL?>session/catalogoVeterinarios?pagina=<?=$i?>"><?=$i?></a></li>
        <?php 
            }
        } ?>

        <?php if($pagina != $total_paginas){ ?>
        <li class="waves-effect"><a href="<?=BASE_URL?>session/catalogoVeterinarios?pagina=<?=$pagina + 1?>"><i class="material-icons">chevron_right</i></a></li>
        <li class="waves-effect"><a href="<?=BASE_URL?>session/catalogoVeterinarios?pagina=<?=$total_paginas?>"><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
        <?php
        }else{ ?>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i></a></li>
            <li class="disabled"><a href=""><i class="material-icons">chevron_right</i><i class="material-icons">chevron_right</i></a></li>
    <?php
        } ?>
    </ul>
</div>

<?php } else { ?>

    <h1>Aun no existen Veterinarios registrados</h1>

<?php } ?>