<nav>
    <div class="container nav-wrapper">
      <a href="<?= BASE_URL; ?>" class="brand-logo">Polipropeludos</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <!-- Botones NavBar-->
        <li><a class='dropdown-trigger btn' href='#' data-target='dropdown1'>Admin</a></li>
        <li><a class='dropdown-trigger btn' href='#' data-target='dropdown2'>Fundacion</a></li>
        <li><a class='dropdown-trigger btn' href='#' data-target='dropdown3'>Tienda</a></li>
        <li><a class='dropdown-trigger btn' href='#' data-target='dropdown4'>Usuario</a></li>

        <!-- Estado de Sesion -->
        <?php
          if(isset($_SESSION['usuario'])){
            $username = $_SESSION['usuario'];
            $rol = $_SESSION['rol'];
              echo "<li>".$username."</li>";
              echo "<li>: ".$rol."</li>";
              echo "<li><a href='". BASE_URL ."admin/index'>Cerrar Sesion</a></li>";
          }
        ?>

        <li>
          <a class="nav-link" href="<?= BASE_URL;?>session/login" role="button" aria-expanded="false">
            <i class="material-icons">account_circle</i>
          </a>
        </li>

        <li>
          <a class="nav-link" href="<?= BASE_URL;?>session/register" role="button" aria-expanded="false">
            <i class="material-icons">edit</i>
          </a>
        </li>

        <!-- Contenido de Dropdowns -->
        <ul id='dropdown1' class='dropdown-content'>
          <li><a href="<?= BASE_URL;?>admin/tipoAnimal">Agregar Tipo Animal</a></li>
          <li><a href="<?= BASE_URL;?>admin/razasAnimal">Agrega Razas</a></li>
          <li><a href="<?= BASE_URL;?>admin/agregaUsuarios">Agrega Usuarios</a></li>
        </ul>

        <ul id='dropdown2' class='dropdown-content'>
          <li><a href="<?= BASE_URL;?>fundacion/agregaAlberg">Agrega Albergue</a></li>
          <li><a href="<?= BASE_URL;?>fundacion/agregaAnimal">Agregar Animal</a></li>
        </ul>

        <ul id='dropdown3' class='dropdown-content'>
          <li><a href="#!">No hay nada xd</a></li>
        </ul>

        <ul id='dropdown4' class='dropdown-content'>
          <li><a href="#!">one</a></li>
          <li><a href="#!">two</a></li>
          <li class="divider" tabindex="-1"></li>
          <li><a href="#!">three</a></li>
          <li><a href="#!"><i class="material-icons">view_module</i>four</a></li>
          <li><a href="#!"><i class="material-icons">cloud</i>five</a></li>
        </ul>

      </ul>
    </div>
  </nav>
  <main>
  <div class="container">
    
