<nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">NavUsuarios</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Agregar
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="<?= BASE_URL;?>home/home">Agrega Usuarios</a></li>
                            <li><a class="dropdown-item" href="#">En desarrollo</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Consultar
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">JAJA ESTO NO ESTA HECHO</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Reportes
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">JAJA ESTO NO ESTA HECHO</a></li>
                        </ul>
                    </li>
                </ul>
                <a class="nav-link" href="<?= BASE_URL;?>session/login" role="button" aria-expanded="false">
                    Login
                </a>
                <a class="nav-link" href="<?= BASE_URL;?>session/login" role="button" aria-expanded="false">
                    Register
                </a>
            </div>
        </div>
    </nav> Este es el Nav