ESTOY EN INDEX.PHTML<br>

<?= "mi variable es: " . $bandera . "<br>" .
"mi variable de programcion: " . $programacion . "<br>";
?>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <i class="fas fa-centercode    "><h1>Peludos Ya!</h1></i>

</body>
</html>
