
<table class="table table-dark table-striped w-50 text-center">
    <thead>
        <tr>
            <th scope="col">Nro</th>
            <th scope="col">Padre</th>
            <th scope="col">Nombre</th>
            <th scope="col">URL</th>
        </tr>
    </thead>
    <tbody>
    <?php
        $tamanio = count($dataMenu);
        for ($i=0; $i < $tamanio; $i++) { 
            echo '<tr>' . 
             '<td>' . $dataMenu[$i]['idmenu'] .'</td>' .
             '<td>'. $dataMenu[$i]['padre'] .'</td>' .
             '<td>'. $dataMenu[$i]['nombre'] .'</td>' .
             '<td>'. $dataMenu[$i]['url'] .'</td>' .
            '</tr>';
        }
     ?>       
    </tbody>
</table>